// Code generated by mockery v2.36.1. DO NOT EDIT.

package api

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	list "github.com/projectcalico/calico/lma/pkg/list"
)

// MockListDestination is an autogenerated mock type for the ListDestination type
type MockListDestination struct {
	mock.Mock
}

// RetrieveList provides a mock function with given fields: kind, from, to, sortAscendingTime
func (_m *MockListDestination) RetrieveList(kind v1.TypeMeta, from *time.Time, to *time.Time, sortAscendingTime bool) (*list.TimestampedResourceList, error) {
	ret := _m.Called(kind, from, to, sortAscendingTime)

	var r0 *list.TimestampedResourceList
	var r1 error
	if rf, ok := ret.Get(0).(func(v1.TypeMeta, *time.Time, *time.Time, bool) (*list.TimestampedResourceList, error)); ok {
		return rf(kind, from, to, sortAscendingTime)
	}
	if rf, ok := ret.Get(0).(func(v1.TypeMeta, *time.Time, *time.Time, bool) *list.TimestampedResourceList); ok {
		r0 = rf(kind, from, to, sortAscendingTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*list.TimestampedResourceList)
		}
	}

	if rf, ok := ret.Get(1).(func(v1.TypeMeta, *time.Time, *time.Time, bool) error); ok {
		r1 = rf(kind, from, to, sortAscendingTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreList provides a mock function with given fields: _a0, _a1
func (_m *MockListDestination) StoreList(_a0 v1.TypeMeta, _a1 *list.TimestampedResourceList) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(v1.TypeMeta, *list.TimestampedResourceList) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockListDestination creates a new instance of MockListDestination. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListDestination(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListDestination {
	mock := &MockListDestination{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
