FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5 AS base

RUN mkdir /code
ADD bin/server-amd64 /code/server

RUN chgrp -R 0 /code && \
    chmod -R g=u /code

FROM scratch

COPY --from=base /code/ /code/

# Add the trusted certs from the ubi image.
COPY --from=base /etc/pki /etc/pki
COPY --from=base /usr/share/pki /usr/share/pki

USER 999

WORKDIR /code
ENTRYPOINT ["/code/server"]