kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   namespace: default
   name: policy-reader
rules:
- apiGroups: [“projectcalico.org”]
  resources: [“policies”]
  verbs: [“get”, “watch”, “list”]

