kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: read-tiers-global
subjects:
 - kind: User
   name: jane
   apiGroup: rbac.authorization.k8s.io
roleRef:
   kind: ClusterRole
   name: tier-reader
   apiGroup: rbac.authorization.k8s.io

