ARG UBI_IMAGE

FROM ${UBI_IMAGE} as ubi

RUN microdnf upgrade


FROM scratch

COPY bin/cnx-queryserver-amd64 /usr/bin/cnx-queryserver

# Copy dependencies from UBI to scratch
COPY --from=ubi /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=ubi /lib64/libpthread.so.0 /lib64/libpthread.so.0
COPY --from=ubi /lib64/libc.so.6 /lib64/libc.so.6

USER 10001:10001

ENTRYPOINT ["/usr/bin/cnx-queryserver"]
