FROM jekyll/minimal
LABEL maintainer="eric@tigera.io"

ENV JEKYLL_UID=501

RUN gem install --no-rdoc --no-ri jekyll-redirect-from
COPY _site /srv/jekyll/_site/
COPY _config.yml /srv/jekyll/

CMD jekyll serve --skip-initial-build --no-watch --config _config.yml > /dev/null 2>&1
