// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	projectcalico "github.com/tigera/apiserver/pkg/apis/projectcalico"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HostEndpointLister helps list HostEndpoints.
type HostEndpointLister interface {
	// List lists all HostEndpoints in the indexer.
	List(selector labels.Selector) (ret []*projectcalico.HostEndpoint, err error)
	// Get retrieves the HostEndpoint from the index for a given name.
	Get(name string) (*projectcalico.HostEndpoint, error)
	HostEndpointListerExpansion
}

// hostEndpointLister implements the HostEndpointLister interface.
type hostEndpointLister struct {
	indexer cache.Indexer
}

// NewHostEndpointLister returns a new HostEndpointLister.
func NewHostEndpointLister(indexer cache.Indexer) HostEndpointLister {
	return &hostEndpointLister{indexer: indexer}
}

// List lists all HostEndpoints in the indexer.
func (s *hostEndpointLister) List(selector labels.Selector) (ret []*projectcalico.HostEndpoint, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*projectcalico.HostEndpoint))
	})
	return ret, err
}

// Get retrieves the HostEndpoint from the index for a given name.
func (s *hostEndpointLister) Get(name string) (*projectcalico.HostEndpoint, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(projectcalico.Resource("hostendpoint"), name)
	}
	return obj.(*projectcalico.HostEndpoint), nil
}
