// Copyright (c) 2019 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	projectcalico "github.com/tigera/calico-k8sapiserver/pkg/apis/projectcalico"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StagedGlobalNetworkPolicyLister helps list StagedGlobalNetworkPolicies.
type StagedGlobalNetworkPolicyLister interface {
	// List lists all StagedGlobalNetworkPolicies in the indexer.
	List(selector labels.Selector) (ret []*projectcalico.StagedGlobalNetworkPolicy, err error)
	// Get retrieves the StagedGlobalNetworkPolicy from the index for a given name.
	Get(name string) (*projectcalico.StagedGlobalNetworkPolicy, error)
	StagedGlobalNetworkPolicyListerExpansion
}

// stagedGlobalNetworkPolicyLister implements the StagedGlobalNetworkPolicyLister interface.
type stagedGlobalNetworkPolicyLister struct {
	indexer cache.Indexer
}

// NewStagedGlobalNetworkPolicyLister returns a new StagedGlobalNetworkPolicyLister.
func NewStagedGlobalNetworkPolicyLister(indexer cache.Indexer) StagedGlobalNetworkPolicyLister {
	return &stagedGlobalNetworkPolicyLister{indexer: indexer}
}

// List lists all StagedGlobalNetworkPolicies in the indexer.
func (s *stagedGlobalNetworkPolicyLister) List(selector labels.Selector) (ret []*projectcalico.StagedGlobalNetworkPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*projectcalico.StagedGlobalNetworkPolicy))
	})
	return ret, err
}

// Get retrieves the StagedGlobalNetworkPolicy from the index for a given name.
func (s *stagedGlobalNetworkPolicyLister) Get(name string) (*projectcalico.StagedGlobalNetworkPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(projectcalico.Resource("stagedglobalnetworkpolicy"), name)
	}
	return obj.(*projectcalico.StagedGlobalNetworkPolicy), nil
}
