// Copyright (c) 2021 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	projectcalico "github.com/projectcalico/apiserver/pkg/apis/projectcalico"
)

// FakeAuthenticationReviews implements AuthenticationReviewInterface
type FakeAuthenticationReviews struct {
	Fake *FakeProjectcalico
}

var authenticationreviewsResource = schema.GroupVersionResource{Group: "projectcalico.org", Version: "", Resource: "authenticationreviews"}

var authenticationreviewsKind = schema.GroupVersionKind{Group: "projectcalico.org", Version: "", Kind: "AuthenticationReview"}

// Get takes name of the authenticationReview, and returns the corresponding authenticationReview object, and an error if there is any.
func (c *FakeAuthenticationReviews) Get(ctx context.Context, name string, options v1.GetOptions) (result *projectcalico.AuthenticationReview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(authenticationreviewsResource, name), &projectcalico.AuthenticationReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.AuthenticationReview), err
}

// List takes label and field selectors, and returns the list of AuthenticationReviews that match those selectors.
func (c *FakeAuthenticationReviews) List(ctx context.Context, opts v1.ListOptions) (result *projectcalico.AuthenticationReviewList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(authenticationreviewsResource, authenticationreviewsKind, opts), &projectcalico.AuthenticationReviewList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &projectcalico.AuthenticationReviewList{ListMeta: obj.(*projectcalico.AuthenticationReviewList).ListMeta}
	for _, item := range obj.(*projectcalico.AuthenticationReviewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested authenticationReviews.
func (c *FakeAuthenticationReviews) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(authenticationreviewsResource, opts))
}

// Create takes the representation of a authenticationReview and creates it.  Returns the server's representation of the authenticationReview, and an error, if there is any.
func (c *FakeAuthenticationReviews) Create(ctx context.Context, authenticationReview *projectcalico.AuthenticationReview, opts v1.CreateOptions) (result *projectcalico.AuthenticationReview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(authenticationreviewsResource, authenticationReview), &projectcalico.AuthenticationReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.AuthenticationReview), err
}

// Update takes the representation of a authenticationReview and updates it. Returns the server's representation of the authenticationReview, and an error, if there is any.
func (c *FakeAuthenticationReviews) Update(ctx context.Context, authenticationReview *projectcalico.AuthenticationReview, opts v1.UpdateOptions) (result *projectcalico.AuthenticationReview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(authenticationreviewsResource, authenticationReview), &projectcalico.AuthenticationReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.AuthenticationReview), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuthenticationReviews) UpdateStatus(ctx context.Context, authenticationReview *projectcalico.AuthenticationReview, opts v1.UpdateOptions) (*projectcalico.AuthenticationReview, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(authenticationreviewsResource, "status", authenticationReview), &projectcalico.AuthenticationReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.AuthenticationReview), err
}

// Delete takes name of the authenticationReview and deletes it. Returns an error if one occurs.
func (c *FakeAuthenticationReviews) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(authenticationreviewsResource, name), &projectcalico.AuthenticationReview{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuthenticationReviews) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(authenticationreviewsResource, listOpts)

	_, err := c.Fake.Invokes(action, &projectcalico.AuthenticationReviewList{})
	return err
}

// Patch applies the patch and returns the patched authenticationReview.
func (c *FakeAuthenticationReviews) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *projectcalico.AuthenticationReview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(authenticationreviewsResource, name, pt, data, subresources...), &projectcalico.AuthenticationReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.AuthenticationReview), err
}
