// Copyright (c) 2019 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	projectcalico "github.com/tigera/calico-k8sapiserver/pkg/apis/projectcalico"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStagedGlobalNetworkPolicies implements StagedGlobalNetworkPolicyInterface
type FakeStagedGlobalNetworkPolicies struct {
	Fake *FakeProjectcalico
}

var stagedglobalnetworkpoliciesResource = schema.GroupVersionResource{Group: "projectcalico.org", Version: "", Resource: "stagedglobalnetworkpolicies"}

var stagedglobalnetworkpoliciesKind = schema.GroupVersionKind{Group: "projectcalico.org", Version: "", Kind: "StagedGlobalNetworkPolicy"}

// Get takes name of the stagedGlobalNetworkPolicy, and returns the corresponding stagedGlobalNetworkPolicy object, and an error if there is any.
func (c *FakeStagedGlobalNetworkPolicies) Get(name string, options v1.GetOptions) (result *projectcalico.StagedGlobalNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(stagedglobalnetworkpoliciesResource, name), &projectcalico.StagedGlobalNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedGlobalNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of StagedGlobalNetworkPolicies that match those selectors.
func (c *FakeStagedGlobalNetworkPolicies) List(opts v1.ListOptions) (result *projectcalico.StagedGlobalNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(stagedglobalnetworkpoliciesResource, stagedglobalnetworkpoliciesKind, opts), &projectcalico.StagedGlobalNetworkPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &projectcalico.StagedGlobalNetworkPolicyList{}
	for _, item := range obj.(*projectcalico.StagedGlobalNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stagedGlobalNetworkPolicies.
func (c *FakeStagedGlobalNetworkPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(stagedglobalnetworkpoliciesResource, opts))
}

// Create takes the representation of a stagedGlobalNetworkPolicy and creates it.  Returns the server's representation of the stagedGlobalNetworkPolicy, and an error, if there is any.
func (c *FakeStagedGlobalNetworkPolicies) Create(stagedGlobalNetworkPolicy *projectcalico.StagedGlobalNetworkPolicy) (result *projectcalico.StagedGlobalNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(stagedglobalnetworkpoliciesResource, stagedGlobalNetworkPolicy), &projectcalico.StagedGlobalNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedGlobalNetworkPolicy), err
}

// Update takes the representation of a stagedGlobalNetworkPolicy and updates it. Returns the server's representation of the stagedGlobalNetworkPolicy, and an error, if there is any.
func (c *FakeStagedGlobalNetworkPolicies) Update(stagedGlobalNetworkPolicy *projectcalico.StagedGlobalNetworkPolicy) (result *projectcalico.StagedGlobalNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(stagedglobalnetworkpoliciesResource, stagedGlobalNetworkPolicy), &projectcalico.StagedGlobalNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedGlobalNetworkPolicy), err
}

// Delete takes name of the stagedGlobalNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeStagedGlobalNetworkPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(stagedglobalnetworkpoliciesResource, name), &projectcalico.StagedGlobalNetworkPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStagedGlobalNetworkPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(stagedglobalnetworkpoliciesResource, listOptions)

	_, err := c.Fake.Invokes(action, &projectcalico.StagedGlobalNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched stagedGlobalNetworkPolicy.
func (c *FakeStagedGlobalNetworkPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *projectcalico.StagedGlobalNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(stagedglobalnetworkpoliciesResource, name, data, subresources...), &projectcalico.StagedGlobalNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedGlobalNetworkPolicy), err
}
