// Copyright (c) 2019 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	projectcalico "github.com/tigera/calico-k8sapiserver/pkg/apis/projectcalico"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStagedKubernetesNetworkPolicies implements StagedKubernetesNetworkPolicyInterface
type FakeStagedKubernetesNetworkPolicies struct {
	Fake *FakeProjectcalico
	ns   string
}

var stagedkubernetesnetworkpoliciesResource = schema.GroupVersionResource{Group: "projectcalico.org", Version: "", Resource: "stagedkubernetesnetworkpolicies"}

var stagedkubernetesnetworkpoliciesKind = schema.GroupVersionKind{Group: "projectcalico.org", Version: "", Kind: "StagedKubernetesNetworkPolicy"}

// Get takes name of the stagedKubernetesNetworkPolicy, and returns the corresponding stagedKubernetesNetworkPolicy object, and an error if there is any.
func (c *FakeStagedKubernetesNetworkPolicies) Get(name string, options v1.GetOptions) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(stagedkubernetesnetworkpoliciesResource, c.ns, name), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of StagedKubernetesNetworkPolicies that match those selectors.
func (c *FakeStagedKubernetesNetworkPolicies) List(opts v1.ListOptions) (result *projectcalico.StagedKubernetesNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(stagedkubernetesnetworkpoliciesResource, stagedkubernetesnetworkpoliciesKind, c.ns, opts), &projectcalico.StagedKubernetesNetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &projectcalico.StagedKubernetesNetworkPolicyList{}
	for _, item := range obj.(*projectcalico.StagedKubernetesNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stagedKubernetesNetworkPolicies.
func (c *FakeStagedKubernetesNetworkPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(stagedkubernetesnetworkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a stagedKubernetesNetworkPolicy and creates it.  Returns the server's representation of the stagedKubernetesNetworkPolicy, and an error, if there is any.
func (c *FakeStagedKubernetesNetworkPolicies) Create(stagedKubernetesNetworkPolicy *projectcalico.StagedKubernetesNetworkPolicy) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(stagedkubernetesnetworkpoliciesResource, c.ns, stagedKubernetesNetworkPolicy), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}

// Update takes the representation of a stagedKubernetesNetworkPolicy and updates it. Returns the server's representation of the stagedKubernetesNetworkPolicy, and an error, if there is any.
func (c *FakeStagedKubernetesNetworkPolicies) Update(stagedKubernetesNetworkPolicy *projectcalico.StagedKubernetesNetworkPolicy) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(stagedkubernetesnetworkpoliciesResource, c.ns, stagedKubernetesNetworkPolicy), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}

// Delete takes name of the stagedKubernetesNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeStagedKubernetesNetworkPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(stagedkubernetesnetworkpoliciesResource, c.ns, name), &projectcalico.StagedKubernetesNetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStagedKubernetesNetworkPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(stagedkubernetesnetworkpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &projectcalico.StagedKubernetesNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched stagedKubernetesNetworkPolicy.
func (c *FakeStagedKubernetesNetworkPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stagedkubernetesnetworkpoliciesResource, c.ns, name, data, subresources...), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}
