// Copyright (c) 2021 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	projectcalico "github.com/projectcalico/apiserver/pkg/apis/projectcalico"
)

// FakeStagedKubernetesNetworkPolicies implements StagedKubernetesNetworkPolicyInterface
type FakeStagedKubernetesNetworkPolicies struct {
	Fake *FakeProjectcalico
	ns   string
}

var stagedkubernetesnetworkpoliciesResource = schema.GroupVersionResource{Group: "projectcalico.org", Version: "", Resource: "stagedkubernetesnetworkpolicies"}

var stagedkubernetesnetworkpoliciesKind = schema.GroupVersionKind{Group: "projectcalico.org", Version: "", Kind: "StagedKubernetesNetworkPolicy"}

// Get takes name of the stagedKubernetesNetworkPolicy, and returns the corresponding stagedKubernetesNetworkPolicy object, and an error if there is any.
func (c *FakeStagedKubernetesNetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(stagedkubernetesnetworkpoliciesResource, c.ns, name), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of StagedKubernetesNetworkPolicies that match those selectors.
func (c *FakeStagedKubernetesNetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *projectcalico.StagedKubernetesNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(stagedkubernetesnetworkpoliciesResource, stagedkubernetesnetworkpoliciesKind, c.ns, opts), &projectcalico.StagedKubernetesNetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &projectcalico.StagedKubernetesNetworkPolicyList{ListMeta: obj.(*projectcalico.StagedKubernetesNetworkPolicyList).ListMeta}
	for _, item := range obj.(*projectcalico.StagedKubernetesNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stagedKubernetesNetworkPolicies.
func (c *FakeStagedKubernetesNetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(stagedkubernetesnetworkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a stagedKubernetesNetworkPolicy and creates it.  Returns the server's representation of the stagedKubernetesNetworkPolicy, and an error, if there is any.
func (c *FakeStagedKubernetesNetworkPolicies) Create(ctx context.Context, stagedKubernetesNetworkPolicy *projectcalico.StagedKubernetesNetworkPolicy, opts v1.CreateOptions) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(stagedkubernetesnetworkpoliciesResource, c.ns, stagedKubernetesNetworkPolicy), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}

// Update takes the representation of a stagedKubernetesNetworkPolicy and updates it. Returns the server's representation of the stagedKubernetesNetworkPolicy, and an error, if there is any.
func (c *FakeStagedKubernetesNetworkPolicies) Update(ctx context.Context, stagedKubernetesNetworkPolicy *projectcalico.StagedKubernetesNetworkPolicy, opts v1.UpdateOptions) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(stagedkubernetesnetworkpoliciesResource, c.ns, stagedKubernetesNetworkPolicy), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}

// Delete takes name of the stagedKubernetesNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeStagedKubernetesNetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(stagedkubernetesnetworkpoliciesResource, c.ns, name), &projectcalico.StagedKubernetesNetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStagedKubernetesNetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(stagedkubernetesnetworkpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &projectcalico.StagedKubernetesNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched stagedKubernetesNetworkPolicy.
func (c *FakeStagedKubernetesNetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *projectcalico.StagedKubernetesNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stagedkubernetesnetworkpoliciesResource, c.ns, name, pt, data, subresources...), &projectcalico.StagedKubernetesNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.StagedKubernetesNetworkPolicy), err
}
