// Copyright (c) 2021 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"

	internalversion "github.com/projectcalico/apiserver/pkg/client/clientset_generated/internalclientset/typed/projectcalico/internalversion"
)

type FakeProjectcalico struct {
	*testing.Fake
}

func (c *FakeProjectcalico) AuthenticationReviews() internalversion.AuthenticationReviewInterface {
	return &FakeAuthenticationReviews{c}
}

func (c *FakeProjectcalico) AuthorizationReviews() internalversion.AuthorizationReviewInterface {
	return &FakeAuthorizationReviews{c}
}

func (c *FakeProjectcalico) BGPConfigurations() internalversion.BGPConfigurationInterface {
	return &FakeBGPConfigurations{c}
}

func (c *FakeProjectcalico) BGPPeers() internalversion.BGPPeerInterface {
	return &FakeBGPPeers{c}
}

func (c *FakeProjectcalico) ClusterInformations() internalversion.ClusterInformationInterface {
	return &FakeClusterInformations{c}
}

func (c *FakeProjectcalico) DeepPacketInspections(namespace string) internalversion.DeepPacketInspectionInterface {
	return &FakeDeepPacketInspections{c, namespace}
}

func (c *FakeProjectcalico) FelixConfigurations() internalversion.FelixConfigurationInterface {
	return &FakeFelixConfigurations{c}
}

func (c *FakeProjectcalico) GlobalAlerts() internalversion.GlobalAlertInterface {
	return &FakeGlobalAlerts{c}
}

func (c *FakeProjectcalico) GlobalAlertTemplates() internalversion.GlobalAlertTemplateInterface {
	return &FakeGlobalAlertTemplates{c}
}

func (c *FakeProjectcalico) GlobalNetworkPolicies() internalversion.GlobalNetworkPolicyInterface {
	return &FakeGlobalNetworkPolicies{c}
}

func (c *FakeProjectcalico) GlobalNetworkSets() internalversion.GlobalNetworkSetInterface {
	return &FakeGlobalNetworkSets{c}
}

func (c *FakeProjectcalico) GlobalReports() internalversion.GlobalReportInterface {
	return &FakeGlobalReports{c}
}

func (c *FakeProjectcalico) GlobalReportTypes() internalversion.GlobalReportTypeInterface {
	return &FakeGlobalReportTypes{c}
}

func (c *FakeProjectcalico) GlobalThreatFeeds() internalversion.GlobalThreatFeedInterface {
	return &FakeGlobalThreatFeeds{c}
}

func (c *FakeProjectcalico) HostEndpoints() internalversion.HostEndpointInterface {
	return &FakeHostEndpoints{c}
}

func (c *FakeProjectcalico) IPPools() internalversion.IPPoolInterface {
	return &FakeIPPools{c}
}

func (c *FakeProjectcalico) KubeControllersConfigurations() internalversion.KubeControllersConfigurationInterface {
	return &FakeKubeControllersConfigurations{c}
}

func (c *FakeProjectcalico) LicenseKeys() internalversion.LicenseKeyInterface {
	return &FakeLicenseKeys{c}
}

func (c *FakeProjectcalico) ManagedClusters() internalversion.ManagedClusterInterface {
	return &FakeManagedClusters{c}
}

func (c *FakeProjectcalico) NetworkPolicies(namespace string) internalversion.NetworkPolicyInterface {
	return &FakeNetworkPolicies{c, namespace}
}

func (c *FakeProjectcalico) NetworkSets() internalversion.NetworkSetInterface {
	return &FakeNetworkSets{c}
}

func (c *FakeProjectcalico) PacketCaptures(namespace string) internalversion.PacketCaptureInterface {
	return &FakePacketCaptures{c, namespace}
}

func (c *FakeProjectcalico) Profiles() internalversion.ProfileInterface {
	return &FakeProfiles{c}
}

func (c *FakeProjectcalico) RemoteClusterConfigurations() internalversion.RemoteClusterConfigurationInterface {
	return &FakeRemoteClusterConfigurations{c}
}

func (c *FakeProjectcalico) StagedGlobalNetworkPolicies() internalversion.StagedGlobalNetworkPolicyInterface {
	return &FakeStagedGlobalNetworkPolicies{c}
}

func (c *FakeProjectcalico) StagedKubernetesNetworkPolicies(namespace string) internalversion.StagedKubernetesNetworkPolicyInterface {
	return &FakeStagedKubernetesNetworkPolicies{c, namespace}
}

func (c *FakeProjectcalico) StagedNetworkPolicies(namespace string) internalversion.StagedNetworkPolicyInterface {
	return &FakeStagedNetworkPolicies{c, namespace}
}

func (c *FakeProjectcalico) Tiers() internalversion.TierInterface {
	return &FakeTiers{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeProjectcalico) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
