#!/bin/sh
# From https://github.com/faisyl/alpine-runit
env > /etc/envvars

if [ "$CALICO_DUAL_TOR" ]; then
    # Pre-Kubernetes dual ToR setup: enable BIRD IPv4 and Dual ToR
    # services; then those will do what's needed.
    mkdir /etc/service/enabled
    cp -a /etc/service/available/bird /etc/service/enabled/
    cp -a /etc/service/available/dual-tor /etc/service/enabled/
else
    # Regular Calico Node startup.
    /etc/rc.local
    retval=$?
    if [ $retval -ne 0 ];
    then
	echo >&2 "Calico node failed to start"
	exit $retval
    fi

    # Export the nodename set by the startup procedure.
    export NODENAME=$(cat /var/lib/calico/nodename)
fi

RUNSVDIR=$(/usr/bin/which runsvdir)
exec ${RUNSVDIR} -P /etc/service/enabled
