apiVersion: v1
kind: Namespace
metadata:
  name: tigera-internal
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tigera-internal
  name: tigera-internal-role
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: [""]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-internal-binding
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: tigera-internal-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tigera-internal-1 
  namespace: tigera-internal
spec:
  selector:
    matchLabels:
      app: tigera-internal-1
  template:
    metadata:
      labels:
        app: tigera-internal-1
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: tigera-internal-1
        image: quay.io/tigera/honeypod:v2.7.0
---
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.ip.enum
spec:
  description: "Alerts on Honeypod accessed via IP enumeration"
  summary: "[Honeypod] Pod subnet IP enumeration by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.ip.enum
spec:
  description: "[Honeypod] Pod subnet IP enumeration by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.port.scan
spec:
  description: "Alerts on Honeypod accessed via port scan"
  summary: "[Honeypod] Pod subnet port scan by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
  metric: count
  condition: gte
  threshold: 4
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.port.scan
spec:
  description: "[Honeypod] Pod subnet port scan by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
  metric: count
  condition: gte
  threshold: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tigera-internal-3
  namespace: tigera-internal
spec:
  selector:
    matchLabels:
      app: tigera-internal-3
  replicas: 1
  template:
    metadata:
      labels:
        app: tigera-internal-3
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: tigera-internal-dashboard
        image: quay.io/tigera/honeypod-exp-service:v2.7.0
        ports:
        - containerPort: 8888
        - containerPort: 443
---
kind: Service
apiVersion: v1
metadata:
  name: tigera-dashboard-internal-debug
  namespace: tigera-internal 
  labels:
    app: tigera-dashboard-internal-debug
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8080
  selector:
    app: tigera-internal-3
---
kind: Service
apiVersion: v1
metadata:
  name: tigera-dashboard-internal-service
  namespace: tigera-internal 
  labels:
    app: tigera-dashboard-internal-service
spec:
  ports:
    - port: 443 
      protocol: TCP
  selector:
    app: tigera-internal-3
---
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.fake.svc
spec:
  description: "Alerts on Honeypod accessed via fake debug service"
  summary: "[Honeypod] Fake debug service accessed by ${source_namespace}/${source_name_aggr} on port 8080"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-3" AND dest_port="8080"'
  aggregateBy: [source_namespace, source_name_aggr]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.fake.svc
spec:
  description: "[Honeypod] Fake debug service accessed by ${source_namespace}/${source_name_aggr} on port 8080"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-3" AND dest_port="8080"'
  aggregateBy: [source_namespace, source_name_aggr]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tigera-internal-4
  namespace: tigera-internal
spec:
  selector:
    matchLabels:
      app: tigera-internal-4
  replicas: 1
  template:
    metadata:
      labels:
        app: tigera-internal-4
    spec:
      containers:
      - name: tigera-internal-4
        image: mysql
        ports:
        - containerPort: 3306
        env:
        #- name: MYSQL_RANDOM_ROOT_PASSWORD
        #- name: MYSQL_ROOT_PASSWORD 
        - name: MYSQL_ALLOW_EMPTY_PASSWORD 
          value: 'yes'
        args: ["--default-authentication-plugin=mysql_native_password"]
---
kind: Service
apiVersion: v1
metadata:
  name: tigera-internal-backend
  namespace: tigera-internal
  labels:
    app: tigera-internal-backend
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: tigera-internal-4
---
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.vuln.svc
spec:
  description: "Alerts on Honeypod accessed via vulnerable (MySQL) service"
  summary: "[Honeypod] Vulnerable service (MySQL) accessed by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-4"'
  aggregateBy: [source_namespace, source_name_aggr]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.vuln.svc
spec:
  description: "[Honeypod] Vulnerable service (MySQL) accessed by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-4"'
  aggregateBy: [source_namespace, source_name_aggr]
---
