# Optional Linseed output
export LINSEED_FLUSH_INTERVAL=${LINSEED_FLUSH_INTERVAL:-5s}
export LINSEED_ENABLED=${LINSEED_ENABLED:-true}
export LINSEED_VERIFY_MODE=${LINSEED_VERIFY_MODE:-peer}
export LINSEED_RETRY_RESPONSE_CODE=${LINSEED_RETRY_RESPONSE_CODE:-500}
