
##### Splunk #####
if [[ "${SPLUNK_AUDIT_LOG}" == "true" || "${SPLUNK_AUDIT_TSEE_LOG}" == "true" || "${SPLUNK_AUDIT_KUBE_LOG}" == "true" || "${SPLUNK_FLOW_LOG}" == "true" ]]; then
  # Splunk defaults 
  export SPLUNK_AUDIT_LOG=${SPLUNK_AUDIT_LOG:-"false"}
  export SPLUNK_AUDIT_TSEE_LOG=${SPLUNK_AUDIT_TSEE_LOG:-"false"}
  export SPLUNK_AUDIT_KUBE_LOG=${SPLUNK_AUDIT_KUBE_LOG:-"false"}
  export SPLUNK_FLOW_LOG=${SPLUNK_FLOW_LOG:-"false"}
  export SPLUNK_HEC_HOST=${SPLUNK_HEC_HOST:-"splunk-hec-host-not-set.com"}
  export SPLUNK_HEC_PORT=${SPLUNK_HEC_PORT:-"8088"}
  export SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN:-"splunk-hec-token-not-set"}
  export SPLUNK_PROTOCOL=${SPLUNK_PROTOCOL:-"https"}
  export SPLUNK_FLUSH_INTERVAL=${SPLUNK_FLUSH_INTERVAL:-"5s"}
  export SPLUNK_FLUSH_THREAD_COUNT=${SPLUNK_FLUSH_THREAD_COUNT:-"2"}
  
  # Optional Splunk audit log output
  export SPLUNK_AUDIT_HEC_HOST=${SPLUNK_AUDIT_HEC_HOST:-$SPLUNK_HEC_HOST}
  export SPLUNK_AUDIT_HEC_PORT=${SPLUNK_AUDIT_HEC_PORT:-$SPLUNK_HEC_PORT}
  export SPLUNK_AUDIT_HEC_TOKEN=${SPLUNK_AUDIT_HEC_TOKEN:-$SPLUNK_HEC_TOKEN}
  export SPLUNK_AUDIT_PROTOCOL=${SPLUNK_AUDIT_PROTOCOL:-$SPLUNK_PROTOCOL}
  export SPLUNK_AUDIT_FLUSH_INTERVAL=${SPLUNK_AUDIT_FLUSH_INTERVAL:-$SPLUNK_FLUSH_INTERVAL}
  export SPLUNK_AUDIT_FLUSH_THREAD_COUNT=${SPLUNK_AUDIT_FLUSH_THREAD_COUNT:-$SPLUNK_FLUSH_THREAD_COUNT}
  export SPLUNK_AUDIT_INDEX=${SPLUNK_AUDIT_INDEX:-$SPLUNK_INDEX}
  export SPLUNK_AUDIT_SOURCETYPE=${SPLUNK_AUDIT_SOURCETYPE:-$SPLUNK_SOURCETYPE}
  export SPLUNK_AUDIT_SOURCE=${SPLUNK_AUDIT_SOURCE:-$SPLUNK_SOURCE}
  
  # Optional Splunk flow log output
  export SPLUNK_FLOW_HEC_HOST=${SPLUNK_FLOW_HEC_HOST:-$SPLUNK_HEC_HOST}
  export SPLUNK_FLOW_HEC_PORT=${SPLUNK_FLOW_HEC_PORT:-$SPLUNK_HEC_PORT}
  export SPLUNK_FLOW_HEC_TOKEN=${SPLUNK_FLOW_HEC_TOKEN:-$SPLUNK_HEC_TOKEN}
  export SPLUNK_FLOW_PROTOCOL=${SPLUNK_FLOW_PROTOCOL:-$SPLUNK_PROTOCOL}
  export SPLUNK_FLOW_FLUSH_INTERVAL=${SPLUNK_FLOW_FLUSH_INTERVAL:-$SPLUNK_FLUSH_INTERVAL}
  export SPLUNK_FLOW_FLUSH_THREAD_COUNT=${SPLUNK_FLOW_FLUSH_THREAD_COUNT:-$SPLUNK_FLUSH_THREAD_COUNT}
  export SPLUNK_FLOW_INDEX=${SPLUNK_FLOW_INDEX:-$SPLUNK_INDEX}
  export SPLUNK_FLOW_SOURCETYPE=${SPLUNK_FLOW_SOURCETYPE:-$SPLUNK_SOURCETYPE}
  export SPLUNK_FLOW_SOURCE=${SPLUNK_FLOW_SOURCE:-$SPLUNK_SOURCE}
fi

