
##### SumoLogic #####
if [[ "${SUMO_AUDIT_LOG}" == "true" || "${SUMO_AUDIT_TSEE_LOG}" == "true" || "${SUMO_AUDIT_KUBE_LOG}" == "true" || "${SUMO_FLOW_LOG}" == "true" ]]; then
  # SumoLogic defaults
  export SUMO_AUDIT_LOG=${SUMO_AUDIT_LOG:-"false"}
  export SUMO_AUDIT_TSEE_LOG=${SUMO_AUDIT_TSEE_LOG:-"false"}
  export SUMO_AUDIT_KUBE_LOG=${SUMO_AUDIT_KUBE_LOG:-"false"}
  export SUMO_FLOW_LOG=${SUMO_FLOW_LOG:-"false"}
  export SUMO_ENDPOINT=${SUMO_ENDPOINT:-"sumo-endpoint-not-set.com"}
  export SUMO_VERIFY_SSL=${SUMO_VERIFY_SSL:-"true"}
  export SUMO_FLUSH_INTERVAL=${SUMO_FLUSH_INTERVAL:-"5s"}
  export SUMO_FLUSH_THREAD_COUNT=${SUMO_FLUSH_THREAD_COUNT:-"2"}

  # Optional SumoLogic audit log output
  export SUMO_AUDIT_ENDPOINT=${SUMO_AUDIT_ENDPOINT:-$SUMO_ENDPOINT}
  export SUMO_AUDIT_VERIFY_SSL=${SUMO_AUDIT_VERIFY_SSL:-$SUMO_VERIFY_SSL}
  export SUMO_AUDIT_SOURCE_CATEGORY=${SUMO_AUDIT_SOURCE_CATEGORY:-$SUMO_SOURCE_CATEGORY}
  export SUMO_AUDIT_SOURCE_NAME=${SUMO_AUDIT_SOURCE_NAME:-$SUMO_SOURCE_NAME}
  export SUMO_AUDIT_SOURCE_HOST=${SUMO_AUDIT_SOURCE_HOST:-$SUMO_SOURCE_HOST}
  export SUMO_AUDIT_FLUSH_INTERVAL=${SUMO_AUDIT_FLUSH_INTERVAL:-$SUMO_FLUSH_INTERVAL}
  export SUMO_AUDIT_FLUSH_THREAD_COUNT=${SUMO_AUDIT_FLUSH_THREAD_COUNT:-$SUMO_FLUSH_THREAD_COUNT}

  # Optional SumoLogic flow log output
  export SUMO_FLOW_ENDPOINT=${SUMO_FLOW_ENDPOINT:-$SUMO_ENDPOINT}
  export SUMO_FLOW_VERIFY_SSL=${SUMO_FLOW_VERIFY_SSL:-$SUMO_VERIFY_SSL}
  export SUMO_FLOW_SOURCE_CATEGORY=${SUMO_FLOW_SOURCE_CATEGORY:-$SUMO_SOURCE_CATEGORY}
  export SUMO_FLOW_SOURCE_NAME=${SUMO_FLOW_SOURCE_NAME:-$SUMO_SOURCE_NAME}
  export SUMO_FLOW_SOURCE_HOST=${SUMO_FLOW_SOURCE_HOST:-$SUMO_SOURCE_HOST}
  export SUMO_FLOW_FLUSH_INTERVAL=${SUMO_FLOW_FLUSH_INTERVAL:-$SUMO_FLUSH_INTERVAL}
  export SUMO_FLOW_FLUSH_THREAD_COUNT=${SUMO_FLOW_FLUSH_THREAD_COUNT:-$SUMO_FLUSH_THREAD_COUNT}
fi

