ARG UBI_IMAGE

FROM ${UBI_IMAGE} as ubi

RUN microdnf upgrade

FROM scratch

ADD bin/packetcapture-amd64 /usr/bin/packetcapture

USER 1001

# Now define the command-line call to start your application
ENTRYPOINT ["/usr/bin/packetcapture"]
