// Copyright (c) 2020-2021 Tigera, Inc. All rights reserved.

package intdataplane

import (
	"errors"

	"github.com/prometheus/client_golang/prometheus"
	log "github.com/sirupsen/logrus"

	"github.com/projectcalico/felix/bpf/events"
)

var (
	bpfEventsCounters = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "felix_bpf_events",
		Help: "Number of events generated by BPF dataplane split by type/cathegory",
	}, []string{"type"})
)

func init() {
	prometheus.MustRegister(bpfEventsCounters)
}

type bpfEventHandler func(e events.Event)

type bpfEventSink struct {
	handlers []bpfEventHandler
	counter  prometheus.Counter
}

type bpfEventPoller struct {
	events events.Events
	sinks  map[events.Type]bpfEventSink

	prometheusLostCounter   prometheus.Counter
	prometheusNoSinkCounter prometheus.Counter
}

func newBpfEventPoller(e events.Events) *bpfEventPoller {
	p := &bpfEventPoller{
		events: e,
		sinks:  make(map[events.Type]bpfEventSink),
	}

	var err error

	// We ignore the errors as this can happen only if there is label mismatch
	p.prometheusLostCounter, err = bpfEventsCounters.GetMetricWithLabelValues("lost")
	if err != nil {
		log.WithError(err).Panic("Failed to create prometheus bpf events lost counter")
	}
	p.prometheusNoSinkCounter, err = bpfEventsCounters.GetMetricWithLabelValues("no_sink")
	if err != nil {
		log.WithError(err).Panic("Failed to create prometheus bpf events no sink counter")
	}

	return p
}

func (p *bpfEventPoller) Register(t events.Type, handler bpfEventHandler) {
	sink, ok := p.sinks[t]
	if !ok {
		var err error
		sink.counter, err = bpfEventsCounters.GetMetricWithLabelValues(t.String())
		if err != nil {
			log.WithError(err).Panicf("Failed to create prometheus bpf events %q counter", t.String())
		}
	}
	sink.handlers = append(sink.handlers, handler)
	p.sinks[t] = sink
}

func (p *bpfEventPoller) Start() error {
	if len(p.sinks) == 0 {
		return errors.New("no event sinks registered")
	}

	go p.run()
	return nil
}

func (p *bpfEventPoller) run() {
	for {
		event, err := p.events.Next()
		if err != nil {
			if lost, ok := err.(events.ErrLostEvents); ok {
				p.prometheusLostCounter.Add(float64(lost))
			}
			log.WithError(err).Warn("Failed to get next event")
			continue
		}

		sink, ok := p.sinks[event.Type()]
		if !ok {
			log.Warnf("Event type %d without a sink", event.Type())
			p.prometheusNoSinkCounter.Inc()
			continue
		}

		for _, handler := range sink.handlers {
			handler(event)
		}
		sink.counter.Inc()
	}
}
