// Code generated by mockery v2.3.0. DO NOT EDIT.

package handler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockHandler) Close() {
	_m.Called()
}

// OnUpdate provides a mock function with given fields: _a0, _a1
func (_m *MockHandler) OnUpdate(_a0 context.Context, _a1 []CacheRequest) {
	_m.Called(_a0, _a1)
}
