ARG UBI_IMAGE

FROM ${UBI_IMAGE} AS ubi

FROM scratch

ADD bin/snapshotter-amd64 /snapshotter

# Copy dependencies from UBI to scratch
COPY --from=ubi /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=ubi /lib64/libpthread.so.0 /lib64/libpthread.so.0
COPY --from=ubi /lib64/libc.so.6 /lib64/libc.so.6

USER 999

WORKDIR /
ENTRYPOINT ["/snapshotter"]
