// +build !ignore_autogenerated

// Copyright (c) 2020 Tigera, Inc. All rights reserved.

// Code generated by conversion-gen. DO NOT EDIT.

package v3

import (
	unsafe "unsafe"

	projectcalico "github.com/tigera/apiserver/pkg/apis/projectcalico"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BGPConfiguration)(nil), (*projectcalico.BGPConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_BGPConfiguration_To_projectcalico_BGPConfiguration(a.(*BGPConfiguration), b.(*projectcalico.BGPConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.BGPConfiguration)(nil), (*BGPConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_BGPConfiguration_To_v3_BGPConfiguration(a.(*projectcalico.BGPConfiguration), b.(*BGPConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BGPConfigurationList)(nil), (*projectcalico.BGPConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_BGPConfigurationList_To_projectcalico_BGPConfigurationList(a.(*BGPConfigurationList), b.(*projectcalico.BGPConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.BGPConfigurationList)(nil), (*BGPConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_BGPConfigurationList_To_v3_BGPConfigurationList(a.(*projectcalico.BGPConfigurationList), b.(*BGPConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BGPPeer)(nil), (*projectcalico.BGPPeer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_BGPPeer_To_projectcalico_BGPPeer(a.(*BGPPeer), b.(*projectcalico.BGPPeer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.BGPPeer)(nil), (*BGPPeer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_BGPPeer_To_v3_BGPPeer(a.(*projectcalico.BGPPeer), b.(*BGPPeer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BGPPeerList)(nil), (*projectcalico.BGPPeerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_BGPPeerList_To_projectcalico_BGPPeerList(a.(*BGPPeerList), b.(*projectcalico.BGPPeerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.BGPPeerList)(nil), (*BGPPeerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_BGPPeerList_To_v3_BGPPeerList(a.(*projectcalico.BGPPeerList), b.(*BGPPeerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterInformation)(nil), (*projectcalico.ClusterInformation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_ClusterInformation_To_projectcalico_ClusterInformation(a.(*ClusterInformation), b.(*projectcalico.ClusterInformation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.ClusterInformation)(nil), (*ClusterInformation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_ClusterInformation_To_v3_ClusterInformation(a.(*projectcalico.ClusterInformation), b.(*ClusterInformation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterInformationList)(nil), (*projectcalico.ClusterInformationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_ClusterInformationList_To_projectcalico_ClusterInformationList(a.(*ClusterInformationList), b.(*projectcalico.ClusterInformationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.ClusterInformationList)(nil), (*ClusterInformationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_ClusterInformationList_To_v3_ClusterInformationList(a.(*projectcalico.ClusterInformationList), b.(*ClusterInformationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FelixConfiguration)(nil), (*projectcalico.FelixConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_FelixConfiguration_To_projectcalico_FelixConfiguration(a.(*FelixConfiguration), b.(*projectcalico.FelixConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.FelixConfiguration)(nil), (*FelixConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_FelixConfiguration_To_v3_FelixConfiguration(a.(*projectcalico.FelixConfiguration), b.(*FelixConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FelixConfigurationList)(nil), (*projectcalico.FelixConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_FelixConfigurationList_To_projectcalico_FelixConfigurationList(a.(*FelixConfigurationList), b.(*projectcalico.FelixConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.FelixConfigurationList)(nil), (*FelixConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_FelixConfigurationList_To_v3_FelixConfigurationList(a.(*projectcalico.FelixConfigurationList), b.(*FelixConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalAlert)(nil), (*projectcalico.GlobalAlert)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalAlert_To_projectcalico_GlobalAlert(a.(*GlobalAlert), b.(*projectcalico.GlobalAlert), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalAlert)(nil), (*GlobalAlert)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalAlert_To_v3_GlobalAlert(a.(*projectcalico.GlobalAlert), b.(*GlobalAlert), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalAlertList)(nil), (*projectcalico.GlobalAlertList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalAlertList_To_projectcalico_GlobalAlertList(a.(*GlobalAlertList), b.(*projectcalico.GlobalAlertList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalAlertList)(nil), (*GlobalAlertList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalAlertList_To_v3_GlobalAlertList(a.(*projectcalico.GlobalAlertList), b.(*GlobalAlertList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalAlertTemplate)(nil), (*projectcalico.GlobalAlertTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalAlertTemplate_To_projectcalico_GlobalAlertTemplate(a.(*GlobalAlertTemplate), b.(*projectcalico.GlobalAlertTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalAlertTemplate)(nil), (*GlobalAlertTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalAlertTemplate_To_v3_GlobalAlertTemplate(a.(*projectcalico.GlobalAlertTemplate), b.(*GlobalAlertTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalAlertTemplateList)(nil), (*projectcalico.GlobalAlertTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalAlertTemplateList_To_projectcalico_GlobalAlertTemplateList(a.(*GlobalAlertTemplateList), b.(*projectcalico.GlobalAlertTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalAlertTemplateList)(nil), (*GlobalAlertTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalAlertTemplateList_To_v3_GlobalAlertTemplateList(a.(*projectcalico.GlobalAlertTemplateList), b.(*GlobalAlertTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalNetworkPolicy)(nil), (*projectcalico.GlobalNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalNetworkPolicy_To_projectcalico_GlobalNetworkPolicy(a.(*GlobalNetworkPolicy), b.(*projectcalico.GlobalNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalNetworkPolicy)(nil), (*GlobalNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalNetworkPolicy_To_v3_GlobalNetworkPolicy(a.(*projectcalico.GlobalNetworkPolicy), b.(*GlobalNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalNetworkPolicyList)(nil), (*projectcalico.GlobalNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalNetworkPolicyList_To_projectcalico_GlobalNetworkPolicyList(a.(*GlobalNetworkPolicyList), b.(*projectcalico.GlobalNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalNetworkPolicyList)(nil), (*GlobalNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalNetworkPolicyList_To_v3_GlobalNetworkPolicyList(a.(*projectcalico.GlobalNetworkPolicyList), b.(*GlobalNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalNetworkSet)(nil), (*projectcalico.GlobalNetworkSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalNetworkSet_To_projectcalico_GlobalNetworkSet(a.(*GlobalNetworkSet), b.(*projectcalico.GlobalNetworkSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalNetworkSet)(nil), (*GlobalNetworkSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalNetworkSet_To_v3_GlobalNetworkSet(a.(*projectcalico.GlobalNetworkSet), b.(*GlobalNetworkSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalNetworkSetList)(nil), (*projectcalico.GlobalNetworkSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalNetworkSetList_To_projectcalico_GlobalNetworkSetList(a.(*GlobalNetworkSetList), b.(*projectcalico.GlobalNetworkSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalNetworkSetList)(nil), (*GlobalNetworkSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalNetworkSetList_To_v3_GlobalNetworkSetList(a.(*projectcalico.GlobalNetworkSetList), b.(*GlobalNetworkSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalReport)(nil), (*projectcalico.GlobalReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalReport_To_projectcalico_GlobalReport(a.(*GlobalReport), b.(*projectcalico.GlobalReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalReport)(nil), (*GlobalReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalReport_To_v3_GlobalReport(a.(*projectcalico.GlobalReport), b.(*GlobalReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalReportList)(nil), (*projectcalico.GlobalReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalReportList_To_projectcalico_GlobalReportList(a.(*GlobalReportList), b.(*projectcalico.GlobalReportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalReportList)(nil), (*GlobalReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalReportList_To_v3_GlobalReportList(a.(*projectcalico.GlobalReportList), b.(*GlobalReportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalReportType)(nil), (*projectcalico.GlobalReportType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalReportType_To_projectcalico_GlobalReportType(a.(*GlobalReportType), b.(*projectcalico.GlobalReportType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalReportType)(nil), (*GlobalReportType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalReportType_To_v3_GlobalReportType(a.(*projectcalico.GlobalReportType), b.(*GlobalReportType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalReportTypeList)(nil), (*projectcalico.GlobalReportTypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalReportTypeList_To_projectcalico_GlobalReportTypeList(a.(*GlobalReportTypeList), b.(*projectcalico.GlobalReportTypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalReportTypeList)(nil), (*GlobalReportTypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalReportTypeList_To_v3_GlobalReportTypeList(a.(*projectcalico.GlobalReportTypeList), b.(*GlobalReportTypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalThreatFeed)(nil), (*projectcalico.GlobalThreatFeed)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalThreatFeed_To_projectcalico_GlobalThreatFeed(a.(*GlobalThreatFeed), b.(*projectcalico.GlobalThreatFeed), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalThreatFeed)(nil), (*GlobalThreatFeed)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalThreatFeed_To_v3_GlobalThreatFeed(a.(*projectcalico.GlobalThreatFeed), b.(*GlobalThreatFeed), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalThreatFeedList)(nil), (*projectcalico.GlobalThreatFeedList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_GlobalThreatFeedList_To_projectcalico_GlobalThreatFeedList(a.(*GlobalThreatFeedList), b.(*projectcalico.GlobalThreatFeedList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.GlobalThreatFeedList)(nil), (*GlobalThreatFeedList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_GlobalThreatFeedList_To_v3_GlobalThreatFeedList(a.(*projectcalico.GlobalThreatFeedList), b.(*GlobalThreatFeedList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostEndpoint)(nil), (*projectcalico.HostEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_HostEndpoint_To_projectcalico_HostEndpoint(a.(*HostEndpoint), b.(*projectcalico.HostEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.HostEndpoint)(nil), (*HostEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_HostEndpoint_To_v3_HostEndpoint(a.(*projectcalico.HostEndpoint), b.(*HostEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostEndpointList)(nil), (*projectcalico.HostEndpointList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_HostEndpointList_To_projectcalico_HostEndpointList(a.(*HostEndpointList), b.(*projectcalico.HostEndpointList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.HostEndpointList)(nil), (*HostEndpointList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_HostEndpointList_To_v3_HostEndpointList(a.(*projectcalico.HostEndpointList), b.(*HostEndpointList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPPool)(nil), (*projectcalico.IPPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_IPPool_To_projectcalico_IPPool(a.(*IPPool), b.(*projectcalico.IPPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.IPPool)(nil), (*IPPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_IPPool_To_v3_IPPool(a.(*projectcalico.IPPool), b.(*IPPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPPoolList)(nil), (*projectcalico.IPPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_IPPoolList_To_projectcalico_IPPoolList(a.(*IPPoolList), b.(*projectcalico.IPPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.IPPoolList)(nil), (*IPPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_IPPoolList_To_v3_IPPoolList(a.(*projectcalico.IPPoolList), b.(*IPPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LicenseKey)(nil), (*projectcalico.LicenseKey)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_LicenseKey_To_projectcalico_LicenseKey(a.(*LicenseKey), b.(*projectcalico.LicenseKey), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.LicenseKey)(nil), (*LicenseKey)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_LicenseKey_To_v3_LicenseKey(a.(*projectcalico.LicenseKey), b.(*LicenseKey), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LicenseKeyList)(nil), (*projectcalico.LicenseKeyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_LicenseKeyList_To_projectcalico_LicenseKeyList(a.(*LicenseKeyList), b.(*projectcalico.LicenseKeyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.LicenseKeyList)(nil), (*LicenseKeyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_LicenseKeyList_To_v3_LicenseKeyList(a.(*projectcalico.LicenseKeyList), b.(*LicenseKeyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedCluster)(nil), (*projectcalico.ManagedCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_ManagedCluster_To_projectcalico_ManagedCluster(a.(*ManagedCluster), b.(*projectcalico.ManagedCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.ManagedCluster)(nil), (*ManagedCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_ManagedCluster_To_v3_ManagedCluster(a.(*projectcalico.ManagedCluster), b.(*ManagedCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedClusterList)(nil), (*projectcalico.ManagedClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_ManagedClusterList_To_projectcalico_ManagedClusterList(a.(*ManagedClusterList), b.(*projectcalico.ManagedClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.ManagedClusterList)(nil), (*ManagedClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_ManagedClusterList_To_v3_ManagedClusterList(a.(*projectcalico.ManagedClusterList), b.(*ManagedClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkPolicy)(nil), (*projectcalico.NetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_NetworkPolicy_To_projectcalico_NetworkPolicy(a.(*NetworkPolicy), b.(*projectcalico.NetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.NetworkPolicy)(nil), (*NetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_NetworkPolicy_To_v3_NetworkPolicy(a.(*projectcalico.NetworkPolicy), b.(*NetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkPolicyList)(nil), (*projectcalico.NetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_NetworkPolicyList_To_projectcalico_NetworkPolicyList(a.(*NetworkPolicyList), b.(*projectcalico.NetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.NetworkPolicyList)(nil), (*NetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_NetworkPolicyList_To_v3_NetworkPolicyList(a.(*projectcalico.NetworkPolicyList), b.(*NetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSet)(nil), (*projectcalico.NetworkSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_NetworkSet_To_projectcalico_NetworkSet(a.(*NetworkSet), b.(*projectcalico.NetworkSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.NetworkSet)(nil), (*NetworkSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_NetworkSet_To_v3_NetworkSet(a.(*projectcalico.NetworkSet), b.(*NetworkSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSetList)(nil), (*projectcalico.NetworkSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_NetworkSetList_To_projectcalico_NetworkSetList(a.(*NetworkSetList), b.(*projectcalico.NetworkSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.NetworkSetList)(nil), (*NetworkSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_NetworkSetList_To_v3_NetworkSetList(a.(*projectcalico.NetworkSetList), b.(*NetworkSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Profile)(nil), (*projectcalico.Profile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_Profile_To_projectcalico_Profile(a.(*Profile), b.(*projectcalico.Profile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.Profile)(nil), (*Profile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_Profile_To_v3_Profile(a.(*projectcalico.Profile), b.(*Profile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProfileList)(nil), (*projectcalico.ProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_ProfileList_To_projectcalico_ProfileList(a.(*ProfileList), b.(*projectcalico.ProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.ProfileList)(nil), (*ProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_ProfileList_To_v3_ProfileList(a.(*projectcalico.ProfileList), b.(*ProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RemoteClusterConfiguration)(nil), (*projectcalico.RemoteClusterConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_RemoteClusterConfiguration_To_projectcalico_RemoteClusterConfiguration(a.(*RemoteClusterConfiguration), b.(*projectcalico.RemoteClusterConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.RemoteClusterConfiguration)(nil), (*RemoteClusterConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_RemoteClusterConfiguration_To_v3_RemoteClusterConfiguration(a.(*projectcalico.RemoteClusterConfiguration), b.(*RemoteClusterConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RemoteClusterConfigurationList)(nil), (*projectcalico.RemoteClusterConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_RemoteClusterConfigurationList_To_projectcalico_RemoteClusterConfigurationList(a.(*RemoteClusterConfigurationList), b.(*projectcalico.RemoteClusterConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.RemoteClusterConfigurationList)(nil), (*RemoteClusterConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_RemoteClusterConfigurationList_To_v3_RemoteClusterConfigurationList(a.(*projectcalico.RemoteClusterConfigurationList), b.(*RemoteClusterConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StagedGlobalNetworkPolicy)(nil), (*projectcalico.StagedGlobalNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_StagedGlobalNetworkPolicy_To_projectcalico_StagedGlobalNetworkPolicy(a.(*StagedGlobalNetworkPolicy), b.(*projectcalico.StagedGlobalNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.StagedGlobalNetworkPolicy)(nil), (*StagedGlobalNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_StagedGlobalNetworkPolicy_To_v3_StagedGlobalNetworkPolicy(a.(*projectcalico.StagedGlobalNetworkPolicy), b.(*StagedGlobalNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StagedGlobalNetworkPolicyList)(nil), (*projectcalico.StagedGlobalNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_StagedGlobalNetworkPolicyList_To_projectcalico_StagedGlobalNetworkPolicyList(a.(*StagedGlobalNetworkPolicyList), b.(*projectcalico.StagedGlobalNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.StagedGlobalNetworkPolicyList)(nil), (*StagedGlobalNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_StagedGlobalNetworkPolicyList_To_v3_StagedGlobalNetworkPolicyList(a.(*projectcalico.StagedGlobalNetworkPolicyList), b.(*StagedGlobalNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StagedKubernetesNetworkPolicy)(nil), (*projectcalico.StagedKubernetesNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_StagedKubernetesNetworkPolicy_To_projectcalico_StagedKubernetesNetworkPolicy(a.(*StagedKubernetesNetworkPolicy), b.(*projectcalico.StagedKubernetesNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.StagedKubernetesNetworkPolicy)(nil), (*StagedKubernetesNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_StagedKubernetesNetworkPolicy_To_v3_StagedKubernetesNetworkPolicy(a.(*projectcalico.StagedKubernetesNetworkPolicy), b.(*StagedKubernetesNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StagedKubernetesNetworkPolicyList)(nil), (*projectcalico.StagedKubernetesNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_StagedKubernetesNetworkPolicyList_To_projectcalico_StagedKubernetesNetworkPolicyList(a.(*StagedKubernetesNetworkPolicyList), b.(*projectcalico.StagedKubernetesNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.StagedKubernetesNetworkPolicyList)(nil), (*StagedKubernetesNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_StagedKubernetesNetworkPolicyList_To_v3_StagedKubernetesNetworkPolicyList(a.(*projectcalico.StagedKubernetesNetworkPolicyList), b.(*StagedKubernetesNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StagedNetworkPolicy)(nil), (*projectcalico.StagedNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_StagedNetworkPolicy_To_projectcalico_StagedNetworkPolicy(a.(*StagedNetworkPolicy), b.(*projectcalico.StagedNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.StagedNetworkPolicy)(nil), (*StagedNetworkPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_StagedNetworkPolicy_To_v3_StagedNetworkPolicy(a.(*projectcalico.StagedNetworkPolicy), b.(*StagedNetworkPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StagedNetworkPolicyList)(nil), (*projectcalico.StagedNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_StagedNetworkPolicyList_To_projectcalico_StagedNetworkPolicyList(a.(*StagedNetworkPolicyList), b.(*projectcalico.StagedNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.StagedNetworkPolicyList)(nil), (*StagedNetworkPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_StagedNetworkPolicyList_To_v3_StagedNetworkPolicyList(a.(*projectcalico.StagedNetworkPolicyList), b.(*StagedNetworkPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Tier)(nil), (*projectcalico.Tier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_Tier_To_projectcalico_Tier(a.(*Tier), b.(*projectcalico.Tier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.Tier)(nil), (*Tier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_Tier_To_v3_Tier(a.(*projectcalico.Tier), b.(*Tier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TierList)(nil), (*projectcalico.TierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v3_TierList_To_projectcalico_TierList(a.(*TierList), b.(*projectcalico.TierList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*projectcalico.TierList)(nil), (*TierList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_projectcalico_TierList_To_v3_TierList(a.(*projectcalico.TierList), b.(*TierList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v3_BGPConfiguration_To_projectcalico_BGPConfiguration(in *BGPConfiguration, out *projectcalico.BGPConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_BGPConfiguration_To_projectcalico_BGPConfiguration is an autogenerated conversion function.
func Convert_v3_BGPConfiguration_To_projectcalico_BGPConfiguration(in *BGPConfiguration, out *projectcalico.BGPConfiguration, s conversion.Scope) error {
	return autoConvert_v3_BGPConfiguration_To_projectcalico_BGPConfiguration(in, out, s)
}

func autoConvert_projectcalico_BGPConfiguration_To_v3_BGPConfiguration(in *projectcalico.BGPConfiguration, out *BGPConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_BGPConfiguration_To_v3_BGPConfiguration is an autogenerated conversion function.
func Convert_projectcalico_BGPConfiguration_To_v3_BGPConfiguration(in *projectcalico.BGPConfiguration, out *BGPConfiguration, s conversion.Scope) error {
	return autoConvert_projectcalico_BGPConfiguration_To_v3_BGPConfiguration(in, out, s)
}

func autoConvert_v3_BGPConfigurationList_To_projectcalico_BGPConfigurationList(in *BGPConfigurationList, out *projectcalico.BGPConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.BGPConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_BGPConfigurationList_To_projectcalico_BGPConfigurationList is an autogenerated conversion function.
func Convert_v3_BGPConfigurationList_To_projectcalico_BGPConfigurationList(in *BGPConfigurationList, out *projectcalico.BGPConfigurationList, s conversion.Scope) error {
	return autoConvert_v3_BGPConfigurationList_To_projectcalico_BGPConfigurationList(in, out, s)
}

func autoConvert_projectcalico_BGPConfigurationList_To_v3_BGPConfigurationList(in *projectcalico.BGPConfigurationList, out *BGPConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BGPConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_BGPConfigurationList_To_v3_BGPConfigurationList is an autogenerated conversion function.
func Convert_projectcalico_BGPConfigurationList_To_v3_BGPConfigurationList(in *projectcalico.BGPConfigurationList, out *BGPConfigurationList, s conversion.Scope) error {
	return autoConvert_projectcalico_BGPConfigurationList_To_v3_BGPConfigurationList(in, out, s)
}

func autoConvert_v3_BGPPeer_To_projectcalico_BGPPeer(in *BGPPeer, out *projectcalico.BGPPeer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_BGPPeer_To_projectcalico_BGPPeer is an autogenerated conversion function.
func Convert_v3_BGPPeer_To_projectcalico_BGPPeer(in *BGPPeer, out *projectcalico.BGPPeer, s conversion.Scope) error {
	return autoConvert_v3_BGPPeer_To_projectcalico_BGPPeer(in, out, s)
}

func autoConvert_projectcalico_BGPPeer_To_v3_BGPPeer(in *projectcalico.BGPPeer, out *BGPPeer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_BGPPeer_To_v3_BGPPeer is an autogenerated conversion function.
func Convert_projectcalico_BGPPeer_To_v3_BGPPeer(in *projectcalico.BGPPeer, out *BGPPeer, s conversion.Scope) error {
	return autoConvert_projectcalico_BGPPeer_To_v3_BGPPeer(in, out, s)
}

func autoConvert_v3_BGPPeerList_To_projectcalico_BGPPeerList(in *BGPPeerList, out *projectcalico.BGPPeerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.BGPPeer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_BGPPeerList_To_projectcalico_BGPPeerList is an autogenerated conversion function.
func Convert_v3_BGPPeerList_To_projectcalico_BGPPeerList(in *BGPPeerList, out *projectcalico.BGPPeerList, s conversion.Scope) error {
	return autoConvert_v3_BGPPeerList_To_projectcalico_BGPPeerList(in, out, s)
}

func autoConvert_projectcalico_BGPPeerList_To_v3_BGPPeerList(in *projectcalico.BGPPeerList, out *BGPPeerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BGPPeer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_BGPPeerList_To_v3_BGPPeerList is an autogenerated conversion function.
func Convert_projectcalico_BGPPeerList_To_v3_BGPPeerList(in *projectcalico.BGPPeerList, out *BGPPeerList, s conversion.Scope) error {
	return autoConvert_projectcalico_BGPPeerList_To_v3_BGPPeerList(in, out, s)
}

func autoConvert_v3_ClusterInformation_To_projectcalico_ClusterInformation(in *ClusterInformation, out *projectcalico.ClusterInformation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_ClusterInformation_To_projectcalico_ClusterInformation is an autogenerated conversion function.
func Convert_v3_ClusterInformation_To_projectcalico_ClusterInformation(in *ClusterInformation, out *projectcalico.ClusterInformation, s conversion.Scope) error {
	return autoConvert_v3_ClusterInformation_To_projectcalico_ClusterInformation(in, out, s)
}

func autoConvert_projectcalico_ClusterInformation_To_v3_ClusterInformation(in *projectcalico.ClusterInformation, out *ClusterInformation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_ClusterInformation_To_v3_ClusterInformation is an autogenerated conversion function.
func Convert_projectcalico_ClusterInformation_To_v3_ClusterInformation(in *projectcalico.ClusterInformation, out *ClusterInformation, s conversion.Scope) error {
	return autoConvert_projectcalico_ClusterInformation_To_v3_ClusterInformation(in, out, s)
}

func autoConvert_v3_ClusterInformationList_To_projectcalico_ClusterInformationList(in *ClusterInformationList, out *projectcalico.ClusterInformationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.ClusterInformation)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_ClusterInformationList_To_projectcalico_ClusterInformationList is an autogenerated conversion function.
func Convert_v3_ClusterInformationList_To_projectcalico_ClusterInformationList(in *ClusterInformationList, out *projectcalico.ClusterInformationList, s conversion.Scope) error {
	return autoConvert_v3_ClusterInformationList_To_projectcalico_ClusterInformationList(in, out, s)
}

func autoConvert_projectcalico_ClusterInformationList_To_v3_ClusterInformationList(in *projectcalico.ClusterInformationList, out *ClusterInformationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterInformation)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_ClusterInformationList_To_v3_ClusterInformationList is an autogenerated conversion function.
func Convert_projectcalico_ClusterInformationList_To_v3_ClusterInformationList(in *projectcalico.ClusterInformationList, out *ClusterInformationList, s conversion.Scope) error {
	return autoConvert_projectcalico_ClusterInformationList_To_v3_ClusterInformationList(in, out, s)
}

func autoConvert_v3_FelixConfiguration_To_projectcalico_FelixConfiguration(in *FelixConfiguration, out *projectcalico.FelixConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_FelixConfiguration_To_projectcalico_FelixConfiguration is an autogenerated conversion function.
func Convert_v3_FelixConfiguration_To_projectcalico_FelixConfiguration(in *FelixConfiguration, out *projectcalico.FelixConfiguration, s conversion.Scope) error {
	return autoConvert_v3_FelixConfiguration_To_projectcalico_FelixConfiguration(in, out, s)
}

func autoConvert_projectcalico_FelixConfiguration_To_v3_FelixConfiguration(in *projectcalico.FelixConfiguration, out *FelixConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_FelixConfiguration_To_v3_FelixConfiguration is an autogenerated conversion function.
func Convert_projectcalico_FelixConfiguration_To_v3_FelixConfiguration(in *projectcalico.FelixConfiguration, out *FelixConfiguration, s conversion.Scope) error {
	return autoConvert_projectcalico_FelixConfiguration_To_v3_FelixConfiguration(in, out, s)
}

func autoConvert_v3_FelixConfigurationList_To_projectcalico_FelixConfigurationList(in *FelixConfigurationList, out *projectcalico.FelixConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.FelixConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_FelixConfigurationList_To_projectcalico_FelixConfigurationList is an autogenerated conversion function.
func Convert_v3_FelixConfigurationList_To_projectcalico_FelixConfigurationList(in *FelixConfigurationList, out *projectcalico.FelixConfigurationList, s conversion.Scope) error {
	return autoConvert_v3_FelixConfigurationList_To_projectcalico_FelixConfigurationList(in, out, s)
}

func autoConvert_projectcalico_FelixConfigurationList_To_v3_FelixConfigurationList(in *projectcalico.FelixConfigurationList, out *FelixConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]FelixConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_FelixConfigurationList_To_v3_FelixConfigurationList is an autogenerated conversion function.
func Convert_projectcalico_FelixConfigurationList_To_v3_FelixConfigurationList(in *projectcalico.FelixConfigurationList, out *FelixConfigurationList, s conversion.Scope) error {
	return autoConvert_projectcalico_FelixConfigurationList_To_v3_FelixConfigurationList(in, out, s)
}

func autoConvert_v3_GlobalAlert_To_projectcalico_GlobalAlert(in *GlobalAlert, out *projectcalico.GlobalAlert, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v3_GlobalAlert_To_projectcalico_GlobalAlert is an autogenerated conversion function.
func Convert_v3_GlobalAlert_To_projectcalico_GlobalAlert(in *GlobalAlert, out *projectcalico.GlobalAlert, s conversion.Scope) error {
	return autoConvert_v3_GlobalAlert_To_projectcalico_GlobalAlert(in, out, s)
}

func autoConvert_projectcalico_GlobalAlert_To_v3_GlobalAlert(in *projectcalico.GlobalAlert, out *GlobalAlert, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_projectcalico_GlobalAlert_To_v3_GlobalAlert is an autogenerated conversion function.
func Convert_projectcalico_GlobalAlert_To_v3_GlobalAlert(in *projectcalico.GlobalAlert, out *GlobalAlert, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalAlert_To_v3_GlobalAlert(in, out, s)
}

func autoConvert_v3_GlobalAlertList_To_projectcalico_GlobalAlertList(in *GlobalAlertList, out *projectcalico.GlobalAlertList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.GlobalAlert)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_GlobalAlertList_To_projectcalico_GlobalAlertList is an autogenerated conversion function.
func Convert_v3_GlobalAlertList_To_projectcalico_GlobalAlertList(in *GlobalAlertList, out *projectcalico.GlobalAlertList, s conversion.Scope) error {
	return autoConvert_v3_GlobalAlertList_To_projectcalico_GlobalAlertList(in, out, s)
}

func autoConvert_projectcalico_GlobalAlertList_To_v3_GlobalAlertList(in *projectcalico.GlobalAlertList, out *GlobalAlertList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalAlert)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_GlobalAlertList_To_v3_GlobalAlertList is an autogenerated conversion function.
func Convert_projectcalico_GlobalAlertList_To_v3_GlobalAlertList(in *projectcalico.GlobalAlertList, out *GlobalAlertList, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalAlertList_To_v3_GlobalAlertList(in, out, s)
}

func autoConvert_v3_GlobalAlertTemplate_To_projectcalico_GlobalAlertTemplate(in *GlobalAlertTemplate, out *projectcalico.GlobalAlertTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_GlobalAlertTemplate_To_projectcalico_GlobalAlertTemplate is an autogenerated conversion function.
func Convert_v3_GlobalAlertTemplate_To_projectcalico_GlobalAlertTemplate(in *GlobalAlertTemplate, out *projectcalico.GlobalAlertTemplate, s conversion.Scope) error {
	return autoConvert_v3_GlobalAlertTemplate_To_projectcalico_GlobalAlertTemplate(in, out, s)
}

func autoConvert_projectcalico_GlobalAlertTemplate_To_v3_GlobalAlertTemplate(in *projectcalico.GlobalAlertTemplate, out *GlobalAlertTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_GlobalAlertTemplate_To_v3_GlobalAlertTemplate is an autogenerated conversion function.
func Convert_projectcalico_GlobalAlertTemplate_To_v3_GlobalAlertTemplate(in *projectcalico.GlobalAlertTemplate, out *GlobalAlertTemplate, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalAlertTemplate_To_v3_GlobalAlertTemplate(in, out, s)
}

func autoConvert_v3_GlobalAlertTemplateList_To_projectcalico_GlobalAlertTemplateList(in *GlobalAlertTemplateList, out *projectcalico.GlobalAlertTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.GlobalAlertTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_GlobalAlertTemplateList_To_projectcalico_GlobalAlertTemplateList is an autogenerated conversion function.
func Convert_v3_GlobalAlertTemplateList_To_projectcalico_GlobalAlertTemplateList(in *GlobalAlertTemplateList, out *projectcalico.GlobalAlertTemplateList, s conversion.Scope) error {
	return autoConvert_v3_GlobalAlertTemplateList_To_projectcalico_GlobalAlertTemplateList(in, out, s)
}

func autoConvert_projectcalico_GlobalAlertTemplateList_To_v3_GlobalAlertTemplateList(in *projectcalico.GlobalAlertTemplateList, out *GlobalAlertTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalAlertTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_GlobalAlertTemplateList_To_v3_GlobalAlertTemplateList is an autogenerated conversion function.
func Convert_projectcalico_GlobalAlertTemplateList_To_v3_GlobalAlertTemplateList(in *projectcalico.GlobalAlertTemplateList, out *GlobalAlertTemplateList, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalAlertTemplateList_To_v3_GlobalAlertTemplateList(in, out, s)
}

func autoConvert_v3_GlobalNetworkPolicy_To_projectcalico_GlobalNetworkPolicy(in *GlobalNetworkPolicy, out *projectcalico.GlobalNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_GlobalNetworkPolicy_To_projectcalico_GlobalNetworkPolicy is an autogenerated conversion function.
func Convert_v3_GlobalNetworkPolicy_To_projectcalico_GlobalNetworkPolicy(in *GlobalNetworkPolicy, out *projectcalico.GlobalNetworkPolicy, s conversion.Scope) error {
	return autoConvert_v3_GlobalNetworkPolicy_To_projectcalico_GlobalNetworkPolicy(in, out, s)
}

func autoConvert_projectcalico_GlobalNetworkPolicy_To_v3_GlobalNetworkPolicy(in *projectcalico.GlobalNetworkPolicy, out *GlobalNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_GlobalNetworkPolicy_To_v3_GlobalNetworkPolicy is an autogenerated conversion function.
func Convert_projectcalico_GlobalNetworkPolicy_To_v3_GlobalNetworkPolicy(in *projectcalico.GlobalNetworkPolicy, out *GlobalNetworkPolicy, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalNetworkPolicy_To_v3_GlobalNetworkPolicy(in, out, s)
}

func autoConvert_v3_GlobalNetworkPolicyList_To_projectcalico_GlobalNetworkPolicyList(in *GlobalNetworkPolicyList, out *projectcalico.GlobalNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.GlobalNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_GlobalNetworkPolicyList_To_projectcalico_GlobalNetworkPolicyList is an autogenerated conversion function.
func Convert_v3_GlobalNetworkPolicyList_To_projectcalico_GlobalNetworkPolicyList(in *GlobalNetworkPolicyList, out *projectcalico.GlobalNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_v3_GlobalNetworkPolicyList_To_projectcalico_GlobalNetworkPolicyList(in, out, s)
}

func autoConvert_projectcalico_GlobalNetworkPolicyList_To_v3_GlobalNetworkPolicyList(in *projectcalico.GlobalNetworkPolicyList, out *GlobalNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_GlobalNetworkPolicyList_To_v3_GlobalNetworkPolicyList is an autogenerated conversion function.
func Convert_projectcalico_GlobalNetworkPolicyList_To_v3_GlobalNetworkPolicyList(in *projectcalico.GlobalNetworkPolicyList, out *GlobalNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalNetworkPolicyList_To_v3_GlobalNetworkPolicyList(in, out, s)
}

func autoConvert_v3_GlobalNetworkSet_To_projectcalico_GlobalNetworkSet(in *GlobalNetworkSet, out *projectcalico.GlobalNetworkSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_GlobalNetworkSet_To_projectcalico_GlobalNetworkSet is an autogenerated conversion function.
func Convert_v3_GlobalNetworkSet_To_projectcalico_GlobalNetworkSet(in *GlobalNetworkSet, out *projectcalico.GlobalNetworkSet, s conversion.Scope) error {
	return autoConvert_v3_GlobalNetworkSet_To_projectcalico_GlobalNetworkSet(in, out, s)
}

func autoConvert_projectcalico_GlobalNetworkSet_To_v3_GlobalNetworkSet(in *projectcalico.GlobalNetworkSet, out *GlobalNetworkSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_GlobalNetworkSet_To_v3_GlobalNetworkSet is an autogenerated conversion function.
func Convert_projectcalico_GlobalNetworkSet_To_v3_GlobalNetworkSet(in *projectcalico.GlobalNetworkSet, out *GlobalNetworkSet, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalNetworkSet_To_v3_GlobalNetworkSet(in, out, s)
}

func autoConvert_v3_GlobalNetworkSetList_To_projectcalico_GlobalNetworkSetList(in *GlobalNetworkSetList, out *projectcalico.GlobalNetworkSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.GlobalNetworkSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_GlobalNetworkSetList_To_projectcalico_GlobalNetworkSetList is an autogenerated conversion function.
func Convert_v3_GlobalNetworkSetList_To_projectcalico_GlobalNetworkSetList(in *GlobalNetworkSetList, out *projectcalico.GlobalNetworkSetList, s conversion.Scope) error {
	return autoConvert_v3_GlobalNetworkSetList_To_projectcalico_GlobalNetworkSetList(in, out, s)
}

func autoConvert_projectcalico_GlobalNetworkSetList_To_v3_GlobalNetworkSetList(in *projectcalico.GlobalNetworkSetList, out *GlobalNetworkSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalNetworkSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_GlobalNetworkSetList_To_v3_GlobalNetworkSetList is an autogenerated conversion function.
func Convert_projectcalico_GlobalNetworkSetList_To_v3_GlobalNetworkSetList(in *projectcalico.GlobalNetworkSetList, out *GlobalNetworkSetList, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalNetworkSetList_To_v3_GlobalNetworkSetList(in, out, s)
}

func autoConvert_v3_GlobalReport_To_projectcalico_GlobalReport(in *GlobalReport, out *projectcalico.GlobalReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v3_GlobalReport_To_projectcalico_GlobalReport is an autogenerated conversion function.
func Convert_v3_GlobalReport_To_projectcalico_GlobalReport(in *GlobalReport, out *projectcalico.GlobalReport, s conversion.Scope) error {
	return autoConvert_v3_GlobalReport_To_projectcalico_GlobalReport(in, out, s)
}

func autoConvert_projectcalico_GlobalReport_To_v3_GlobalReport(in *projectcalico.GlobalReport, out *GlobalReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_projectcalico_GlobalReport_To_v3_GlobalReport is an autogenerated conversion function.
func Convert_projectcalico_GlobalReport_To_v3_GlobalReport(in *projectcalico.GlobalReport, out *GlobalReport, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalReport_To_v3_GlobalReport(in, out, s)
}

func autoConvert_v3_GlobalReportList_To_projectcalico_GlobalReportList(in *GlobalReportList, out *projectcalico.GlobalReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.GlobalReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_GlobalReportList_To_projectcalico_GlobalReportList is an autogenerated conversion function.
func Convert_v3_GlobalReportList_To_projectcalico_GlobalReportList(in *GlobalReportList, out *projectcalico.GlobalReportList, s conversion.Scope) error {
	return autoConvert_v3_GlobalReportList_To_projectcalico_GlobalReportList(in, out, s)
}

func autoConvert_projectcalico_GlobalReportList_To_v3_GlobalReportList(in *projectcalico.GlobalReportList, out *GlobalReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_GlobalReportList_To_v3_GlobalReportList is an autogenerated conversion function.
func Convert_projectcalico_GlobalReportList_To_v3_GlobalReportList(in *projectcalico.GlobalReportList, out *GlobalReportList, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalReportList_To_v3_GlobalReportList(in, out, s)
}

func autoConvert_v3_GlobalReportType_To_projectcalico_GlobalReportType(in *GlobalReportType, out *projectcalico.GlobalReportType, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_GlobalReportType_To_projectcalico_GlobalReportType is an autogenerated conversion function.
func Convert_v3_GlobalReportType_To_projectcalico_GlobalReportType(in *GlobalReportType, out *projectcalico.GlobalReportType, s conversion.Scope) error {
	return autoConvert_v3_GlobalReportType_To_projectcalico_GlobalReportType(in, out, s)
}

func autoConvert_projectcalico_GlobalReportType_To_v3_GlobalReportType(in *projectcalico.GlobalReportType, out *GlobalReportType, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_GlobalReportType_To_v3_GlobalReportType is an autogenerated conversion function.
func Convert_projectcalico_GlobalReportType_To_v3_GlobalReportType(in *projectcalico.GlobalReportType, out *GlobalReportType, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalReportType_To_v3_GlobalReportType(in, out, s)
}

func autoConvert_v3_GlobalReportTypeList_To_projectcalico_GlobalReportTypeList(in *GlobalReportTypeList, out *projectcalico.GlobalReportTypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.GlobalReportType)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_GlobalReportTypeList_To_projectcalico_GlobalReportTypeList is an autogenerated conversion function.
func Convert_v3_GlobalReportTypeList_To_projectcalico_GlobalReportTypeList(in *GlobalReportTypeList, out *projectcalico.GlobalReportTypeList, s conversion.Scope) error {
	return autoConvert_v3_GlobalReportTypeList_To_projectcalico_GlobalReportTypeList(in, out, s)
}

func autoConvert_projectcalico_GlobalReportTypeList_To_v3_GlobalReportTypeList(in *projectcalico.GlobalReportTypeList, out *GlobalReportTypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalReportType)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_GlobalReportTypeList_To_v3_GlobalReportTypeList is an autogenerated conversion function.
func Convert_projectcalico_GlobalReportTypeList_To_v3_GlobalReportTypeList(in *projectcalico.GlobalReportTypeList, out *GlobalReportTypeList, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalReportTypeList_To_v3_GlobalReportTypeList(in, out, s)
}

func autoConvert_v3_GlobalThreatFeed_To_projectcalico_GlobalThreatFeed(in *GlobalThreatFeed, out *projectcalico.GlobalThreatFeed, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v3_GlobalThreatFeed_To_projectcalico_GlobalThreatFeed is an autogenerated conversion function.
func Convert_v3_GlobalThreatFeed_To_projectcalico_GlobalThreatFeed(in *GlobalThreatFeed, out *projectcalico.GlobalThreatFeed, s conversion.Scope) error {
	return autoConvert_v3_GlobalThreatFeed_To_projectcalico_GlobalThreatFeed(in, out, s)
}

func autoConvert_projectcalico_GlobalThreatFeed_To_v3_GlobalThreatFeed(in *projectcalico.GlobalThreatFeed, out *GlobalThreatFeed, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_projectcalico_GlobalThreatFeed_To_v3_GlobalThreatFeed is an autogenerated conversion function.
func Convert_projectcalico_GlobalThreatFeed_To_v3_GlobalThreatFeed(in *projectcalico.GlobalThreatFeed, out *GlobalThreatFeed, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalThreatFeed_To_v3_GlobalThreatFeed(in, out, s)
}

func autoConvert_v3_GlobalThreatFeedList_To_projectcalico_GlobalThreatFeedList(in *GlobalThreatFeedList, out *projectcalico.GlobalThreatFeedList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.GlobalThreatFeed)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_GlobalThreatFeedList_To_projectcalico_GlobalThreatFeedList is an autogenerated conversion function.
func Convert_v3_GlobalThreatFeedList_To_projectcalico_GlobalThreatFeedList(in *GlobalThreatFeedList, out *projectcalico.GlobalThreatFeedList, s conversion.Scope) error {
	return autoConvert_v3_GlobalThreatFeedList_To_projectcalico_GlobalThreatFeedList(in, out, s)
}

func autoConvert_projectcalico_GlobalThreatFeedList_To_v3_GlobalThreatFeedList(in *projectcalico.GlobalThreatFeedList, out *GlobalThreatFeedList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalThreatFeed)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_GlobalThreatFeedList_To_v3_GlobalThreatFeedList is an autogenerated conversion function.
func Convert_projectcalico_GlobalThreatFeedList_To_v3_GlobalThreatFeedList(in *projectcalico.GlobalThreatFeedList, out *GlobalThreatFeedList, s conversion.Scope) error {
	return autoConvert_projectcalico_GlobalThreatFeedList_To_v3_GlobalThreatFeedList(in, out, s)
}

func autoConvert_v3_HostEndpoint_To_projectcalico_HostEndpoint(in *HostEndpoint, out *projectcalico.HostEndpoint, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_HostEndpoint_To_projectcalico_HostEndpoint is an autogenerated conversion function.
func Convert_v3_HostEndpoint_To_projectcalico_HostEndpoint(in *HostEndpoint, out *projectcalico.HostEndpoint, s conversion.Scope) error {
	return autoConvert_v3_HostEndpoint_To_projectcalico_HostEndpoint(in, out, s)
}

func autoConvert_projectcalico_HostEndpoint_To_v3_HostEndpoint(in *projectcalico.HostEndpoint, out *HostEndpoint, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_HostEndpoint_To_v3_HostEndpoint is an autogenerated conversion function.
func Convert_projectcalico_HostEndpoint_To_v3_HostEndpoint(in *projectcalico.HostEndpoint, out *HostEndpoint, s conversion.Scope) error {
	return autoConvert_projectcalico_HostEndpoint_To_v3_HostEndpoint(in, out, s)
}

func autoConvert_v3_HostEndpointList_To_projectcalico_HostEndpointList(in *HostEndpointList, out *projectcalico.HostEndpointList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.HostEndpoint)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_HostEndpointList_To_projectcalico_HostEndpointList is an autogenerated conversion function.
func Convert_v3_HostEndpointList_To_projectcalico_HostEndpointList(in *HostEndpointList, out *projectcalico.HostEndpointList, s conversion.Scope) error {
	return autoConvert_v3_HostEndpointList_To_projectcalico_HostEndpointList(in, out, s)
}

func autoConvert_projectcalico_HostEndpointList_To_v3_HostEndpointList(in *projectcalico.HostEndpointList, out *HostEndpointList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HostEndpoint)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_HostEndpointList_To_v3_HostEndpointList is an autogenerated conversion function.
func Convert_projectcalico_HostEndpointList_To_v3_HostEndpointList(in *projectcalico.HostEndpointList, out *HostEndpointList, s conversion.Scope) error {
	return autoConvert_projectcalico_HostEndpointList_To_v3_HostEndpointList(in, out, s)
}

func autoConvert_v3_IPPool_To_projectcalico_IPPool(in *IPPool, out *projectcalico.IPPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_IPPool_To_projectcalico_IPPool is an autogenerated conversion function.
func Convert_v3_IPPool_To_projectcalico_IPPool(in *IPPool, out *projectcalico.IPPool, s conversion.Scope) error {
	return autoConvert_v3_IPPool_To_projectcalico_IPPool(in, out, s)
}

func autoConvert_projectcalico_IPPool_To_v3_IPPool(in *projectcalico.IPPool, out *IPPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_IPPool_To_v3_IPPool is an autogenerated conversion function.
func Convert_projectcalico_IPPool_To_v3_IPPool(in *projectcalico.IPPool, out *IPPool, s conversion.Scope) error {
	return autoConvert_projectcalico_IPPool_To_v3_IPPool(in, out, s)
}

func autoConvert_v3_IPPoolList_To_projectcalico_IPPoolList(in *IPPoolList, out *projectcalico.IPPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.IPPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_IPPoolList_To_projectcalico_IPPoolList is an autogenerated conversion function.
func Convert_v3_IPPoolList_To_projectcalico_IPPoolList(in *IPPoolList, out *projectcalico.IPPoolList, s conversion.Scope) error {
	return autoConvert_v3_IPPoolList_To_projectcalico_IPPoolList(in, out, s)
}

func autoConvert_projectcalico_IPPoolList_To_v3_IPPoolList(in *projectcalico.IPPoolList, out *IPPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IPPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_IPPoolList_To_v3_IPPoolList is an autogenerated conversion function.
func Convert_projectcalico_IPPoolList_To_v3_IPPoolList(in *projectcalico.IPPoolList, out *IPPoolList, s conversion.Scope) error {
	return autoConvert_projectcalico_IPPoolList_To_v3_IPPoolList(in, out, s)
}

func autoConvert_v3_LicenseKey_To_projectcalico_LicenseKey(in *LicenseKey, out *projectcalico.LicenseKey, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_LicenseKey_To_projectcalico_LicenseKey is an autogenerated conversion function.
func Convert_v3_LicenseKey_To_projectcalico_LicenseKey(in *LicenseKey, out *projectcalico.LicenseKey, s conversion.Scope) error {
	return autoConvert_v3_LicenseKey_To_projectcalico_LicenseKey(in, out, s)
}

func autoConvert_projectcalico_LicenseKey_To_v3_LicenseKey(in *projectcalico.LicenseKey, out *LicenseKey, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_LicenseKey_To_v3_LicenseKey is an autogenerated conversion function.
func Convert_projectcalico_LicenseKey_To_v3_LicenseKey(in *projectcalico.LicenseKey, out *LicenseKey, s conversion.Scope) error {
	return autoConvert_projectcalico_LicenseKey_To_v3_LicenseKey(in, out, s)
}

func autoConvert_v3_LicenseKeyList_To_projectcalico_LicenseKeyList(in *LicenseKeyList, out *projectcalico.LicenseKeyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.LicenseKey)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_LicenseKeyList_To_projectcalico_LicenseKeyList is an autogenerated conversion function.
func Convert_v3_LicenseKeyList_To_projectcalico_LicenseKeyList(in *LicenseKeyList, out *projectcalico.LicenseKeyList, s conversion.Scope) error {
	return autoConvert_v3_LicenseKeyList_To_projectcalico_LicenseKeyList(in, out, s)
}

func autoConvert_projectcalico_LicenseKeyList_To_v3_LicenseKeyList(in *projectcalico.LicenseKeyList, out *LicenseKeyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]LicenseKey)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_LicenseKeyList_To_v3_LicenseKeyList is an autogenerated conversion function.
func Convert_projectcalico_LicenseKeyList_To_v3_LicenseKeyList(in *projectcalico.LicenseKeyList, out *LicenseKeyList, s conversion.Scope) error {
	return autoConvert_projectcalico_LicenseKeyList_To_v3_LicenseKeyList(in, out, s)
}

func autoConvert_v3_ManagedCluster_To_projectcalico_ManagedCluster(in *ManagedCluster, out *projectcalico.ManagedCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v3_ManagedCluster_To_projectcalico_ManagedCluster is an autogenerated conversion function.
func Convert_v3_ManagedCluster_To_projectcalico_ManagedCluster(in *ManagedCluster, out *projectcalico.ManagedCluster, s conversion.Scope) error {
	return autoConvert_v3_ManagedCluster_To_projectcalico_ManagedCluster(in, out, s)
}

func autoConvert_projectcalico_ManagedCluster_To_v3_ManagedCluster(in *projectcalico.ManagedCluster, out *ManagedCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_projectcalico_ManagedCluster_To_v3_ManagedCluster is an autogenerated conversion function.
func Convert_projectcalico_ManagedCluster_To_v3_ManagedCluster(in *projectcalico.ManagedCluster, out *ManagedCluster, s conversion.Scope) error {
	return autoConvert_projectcalico_ManagedCluster_To_v3_ManagedCluster(in, out, s)
}

func autoConvert_v3_ManagedClusterList_To_projectcalico_ManagedClusterList(in *ManagedClusterList, out *projectcalico.ManagedClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.ManagedCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_ManagedClusterList_To_projectcalico_ManagedClusterList is an autogenerated conversion function.
func Convert_v3_ManagedClusterList_To_projectcalico_ManagedClusterList(in *ManagedClusterList, out *projectcalico.ManagedClusterList, s conversion.Scope) error {
	return autoConvert_v3_ManagedClusterList_To_projectcalico_ManagedClusterList(in, out, s)
}

func autoConvert_projectcalico_ManagedClusterList_To_v3_ManagedClusterList(in *projectcalico.ManagedClusterList, out *ManagedClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ManagedCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_ManagedClusterList_To_v3_ManagedClusterList is an autogenerated conversion function.
func Convert_projectcalico_ManagedClusterList_To_v3_ManagedClusterList(in *projectcalico.ManagedClusterList, out *ManagedClusterList, s conversion.Scope) error {
	return autoConvert_projectcalico_ManagedClusterList_To_v3_ManagedClusterList(in, out, s)
}

func autoConvert_v3_NetworkPolicy_To_projectcalico_NetworkPolicy(in *NetworkPolicy, out *projectcalico.NetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_NetworkPolicy_To_projectcalico_NetworkPolicy is an autogenerated conversion function.
func Convert_v3_NetworkPolicy_To_projectcalico_NetworkPolicy(in *NetworkPolicy, out *projectcalico.NetworkPolicy, s conversion.Scope) error {
	return autoConvert_v3_NetworkPolicy_To_projectcalico_NetworkPolicy(in, out, s)
}

func autoConvert_projectcalico_NetworkPolicy_To_v3_NetworkPolicy(in *projectcalico.NetworkPolicy, out *NetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_NetworkPolicy_To_v3_NetworkPolicy is an autogenerated conversion function.
func Convert_projectcalico_NetworkPolicy_To_v3_NetworkPolicy(in *projectcalico.NetworkPolicy, out *NetworkPolicy, s conversion.Scope) error {
	return autoConvert_projectcalico_NetworkPolicy_To_v3_NetworkPolicy(in, out, s)
}

func autoConvert_v3_NetworkPolicyList_To_projectcalico_NetworkPolicyList(in *NetworkPolicyList, out *projectcalico.NetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.NetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_NetworkPolicyList_To_projectcalico_NetworkPolicyList is an autogenerated conversion function.
func Convert_v3_NetworkPolicyList_To_projectcalico_NetworkPolicyList(in *NetworkPolicyList, out *projectcalico.NetworkPolicyList, s conversion.Scope) error {
	return autoConvert_v3_NetworkPolicyList_To_projectcalico_NetworkPolicyList(in, out, s)
}

func autoConvert_projectcalico_NetworkPolicyList_To_v3_NetworkPolicyList(in *projectcalico.NetworkPolicyList, out *NetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_NetworkPolicyList_To_v3_NetworkPolicyList is an autogenerated conversion function.
func Convert_projectcalico_NetworkPolicyList_To_v3_NetworkPolicyList(in *projectcalico.NetworkPolicyList, out *NetworkPolicyList, s conversion.Scope) error {
	return autoConvert_projectcalico_NetworkPolicyList_To_v3_NetworkPolicyList(in, out, s)
}

func autoConvert_v3_NetworkSet_To_projectcalico_NetworkSet(in *NetworkSet, out *projectcalico.NetworkSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_NetworkSet_To_projectcalico_NetworkSet is an autogenerated conversion function.
func Convert_v3_NetworkSet_To_projectcalico_NetworkSet(in *NetworkSet, out *projectcalico.NetworkSet, s conversion.Scope) error {
	return autoConvert_v3_NetworkSet_To_projectcalico_NetworkSet(in, out, s)
}

func autoConvert_projectcalico_NetworkSet_To_v3_NetworkSet(in *projectcalico.NetworkSet, out *NetworkSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_NetworkSet_To_v3_NetworkSet is an autogenerated conversion function.
func Convert_projectcalico_NetworkSet_To_v3_NetworkSet(in *projectcalico.NetworkSet, out *NetworkSet, s conversion.Scope) error {
	return autoConvert_projectcalico_NetworkSet_To_v3_NetworkSet(in, out, s)
}

func autoConvert_v3_NetworkSetList_To_projectcalico_NetworkSetList(in *NetworkSetList, out *projectcalico.NetworkSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.NetworkSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_NetworkSetList_To_projectcalico_NetworkSetList is an autogenerated conversion function.
func Convert_v3_NetworkSetList_To_projectcalico_NetworkSetList(in *NetworkSetList, out *projectcalico.NetworkSetList, s conversion.Scope) error {
	return autoConvert_v3_NetworkSetList_To_projectcalico_NetworkSetList(in, out, s)
}

func autoConvert_projectcalico_NetworkSetList_To_v3_NetworkSetList(in *projectcalico.NetworkSetList, out *NetworkSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NetworkSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_NetworkSetList_To_v3_NetworkSetList is an autogenerated conversion function.
func Convert_projectcalico_NetworkSetList_To_v3_NetworkSetList(in *projectcalico.NetworkSetList, out *NetworkSetList, s conversion.Scope) error {
	return autoConvert_projectcalico_NetworkSetList_To_v3_NetworkSetList(in, out, s)
}

func autoConvert_v3_Profile_To_projectcalico_Profile(in *Profile, out *projectcalico.Profile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_Profile_To_projectcalico_Profile is an autogenerated conversion function.
func Convert_v3_Profile_To_projectcalico_Profile(in *Profile, out *projectcalico.Profile, s conversion.Scope) error {
	return autoConvert_v3_Profile_To_projectcalico_Profile(in, out, s)
}

func autoConvert_projectcalico_Profile_To_v3_Profile(in *projectcalico.Profile, out *Profile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_Profile_To_v3_Profile is an autogenerated conversion function.
func Convert_projectcalico_Profile_To_v3_Profile(in *projectcalico.Profile, out *Profile, s conversion.Scope) error {
	return autoConvert_projectcalico_Profile_To_v3_Profile(in, out, s)
}

func autoConvert_v3_ProfileList_To_projectcalico_ProfileList(in *ProfileList, out *projectcalico.ProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.Profile)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_ProfileList_To_projectcalico_ProfileList is an autogenerated conversion function.
func Convert_v3_ProfileList_To_projectcalico_ProfileList(in *ProfileList, out *projectcalico.ProfileList, s conversion.Scope) error {
	return autoConvert_v3_ProfileList_To_projectcalico_ProfileList(in, out, s)
}

func autoConvert_projectcalico_ProfileList_To_v3_ProfileList(in *projectcalico.ProfileList, out *ProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Profile)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_ProfileList_To_v3_ProfileList is an autogenerated conversion function.
func Convert_projectcalico_ProfileList_To_v3_ProfileList(in *projectcalico.ProfileList, out *ProfileList, s conversion.Scope) error {
	return autoConvert_projectcalico_ProfileList_To_v3_ProfileList(in, out, s)
}

func autoConvert_v3_RemoteClusterConfiguration_To_projectcalico_RemoteClusterConfiguration(in *RemoteClusterConfiguration, out *projectcalico.RemoteClusterConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_RemoteClusterConfiguration_To_projectcalico_RemoteClusterConfiguration is an autogenerated conversion function.
func Convert_v3_RemoteClusterConfiguration_To_projectcalico_RemoteClusterConfiguration(in *RemoteClusterConfiguration, out *projectcalico.RemoteClusterConfiguration, s conversion.Scope) error {
	return autoConvert_v3_RemoteClusterConfiguration_To_projectcalico_RemoteClusterConfiguration(in, out, s)
}

func autoConvert_projectcalico_RemoteClusterConfiguration_To_v3_RemoteClusterConfiguration(in *projectcalico.RemoteClusterConfiguration, out *RemoteClusterConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_RemoteClusterConfiguration_To_v3_RemoteClusterConfiguration is an autogenerated conversion function.
func Convert_projectcalico_RemoteClusterConfiguration_To_v3_RemoteClusterConfiguration(in *projectcalico.RemoteClusterConfiguration, out *RemoteClusterConfiguration, s conversion.Scope) error {
	return autoConvert_projectcalico_RemoteClusterConfiguration_To_v3_RemoteClusterConfiguration(in, out, s)
}

func autoConvert_v3_RemoteClusterConfigurationList_To_projectcalico_RemoteClusterConfigurationList(in *RemoteClusterConfigurationList, out *projectcalico.RemoteClusterConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.RemoteClusterConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_RemoteClusterConfigurationList_To_projectcalico_RemoteClusterConfigurationList is an autogenerated conversion function.
func Convert_v3_RemoteClusterConfigurationList_To_projectcalico_RemoteClusterConfigurationList(in *RemoteClusterConfigurationList, out *projectcalico.RemoteClusterConfigurationList, s conversion.Scope) error {
	return autoConvert_v3_RemoteClusterConfigurationList_To_projectcalico_RemoteClusterConfigurationList(in, out, s)
}

func autoConvert_projectcalico_RemoteClusterConfigurationList_To_v3_RemoteClusterConfigurationList(in *projectcalico.RemoteClusterConfigurationList, out *RemoteClusterConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RemoteClusterConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_RemoteClusterConfigurationList_To_v3_RemoteClusterConfigurationList is an autogenerated conversion function.
func Convert_projectcalico_RemoteClusterConfigurationList_To_v3_RemoteClusterConfigurationList(in *projectcalico.RemoteClusterConfigurationList, out *RemoteClusterConfigurationList, s conversion.Scope) error {
	return autoConvert_projectcalico_RemoteClusterConfigurationList_To_v3_RemoteClusterConfigurationList(in, out, s)
}

func autoConvert_v3_StagedGlobalNetworkPolicy_To_projectcalico_StagedGlobalNetworkPolicy(in *StagedGlobalNetworkPolicy, out *projectcalico.StagedGlobalNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_StagedGlobalNetworkPolicy_To_projectcalico_StagedGlobalNetworkPolicy is an autogenerated conversion function.
func Convert_v3_StagedGlobalNetworkPolicy_To_projectcalico_StagedGlobalNetworkPolicy(in *StagedGlobalNetworkPolicy, out *projectcalico.StagedGlobalNetworkPolicy, s conversion.Scope) error {
	return autoConvert_v3_StagedGlobalNetworkPolicy_To_projectcalico_StagedGlobalNetworkPolicy(in, out, s)
}

func autoConvert_projectcalico_StagedGlobalNetworkPolicy_To_v3_StagedGlobalNetworkPolicy(in *projectcalico.StagedGlobalNetworkPolicy, out *StagedGlobalNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_StagedGlobalNetworkPolicy_To_v3_StagedGlobalNetworkPolicy is an autogenerated conversion function.
func Convert_projectcalico_StagedGlobalNetworkPolicy_To_v3_StagedGlobalNetworkPolicy(in *projectcalico.StagedGlobalNetworkPolicy, out *StagedGlobalNetworkPolicy, s conversion.Scope) error {
	return autoConvert_projectcalico_StagedGlobalNetworkPolicy_To_v3_StagedGlobalNetworkPolicy(in, out, s)
}

func autoConvert_v3_StagedGlobalNetworkPolicyList_To_projectcalico_StagedGlobalNetworkPolicyList(in *StagedGlobalNetworkPolicyList, out *projectcalico.StagedGlobalNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.StagedGlobalNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_StagedGlobalNetworkPolicyList_To_projectcalico_StagedGlobalNetworkPolicyList is an autogenerated conversion function.
func Convert_v3_StagedGlobalNetworkPolicyList_To_projectcalico_StagedGlobalNetworkPolicyList(in *StagedGlobalNetworkPolicyList, out *projectcalico.StagedGlobalNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_v3_StagedGlobalNetworkPolicyList_To_projectcalico_StagedGlobalNetworkPolicyList(in, out, s)
}

func autoConvert_projectcalico_StagedGlobalNetworkPolicyList_To_v3_StagedGlobalNetworkPolicyList(in *projectcalico.StagedGlobalNetworkPolicyList, out *StagedGlobalNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]StagedGlobalNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_StagedGlobalNetworkPolicyList_To_v3_StagedGlobalNetworkPolicyList is an autogenerated conversion function.
func Convert_projectcalico_StagedGlobalNetworkPolicyList_To_v3_StagedGlobalNetworkPolicyList(in *projectcalico.StagedGlobalNetworkPolicyList, out *StagedGlobalNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_projectcalico_StagedGlobalNetworkPolicyList_To_v3_StagedGlobalNetworkPolicyList(in, out, s)
}

func autoConvert_v3_StagedKubernetesNetworkPolicy_To_projectcalico_StagedKubernetesNetworkPolicy(in *StagedKubernetesNetworkPolicy, out *projectcalico.StagedKubernetesNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_StagedKubernetesNetworkPolicy_To_projectcalico_StagedKubernetesNetworkPolicy is an autogenerated conversion function.
func Convert_v3_StagedKubernetesNetworkPolicy_To_projectcalico_StagedKubernetesNetworkPolicy(in *StagedKubernetesNetworkPolicy, out *projectcalico.StagedKubernetesNetworkPolicy, s conversion.Scope) error {
	return autoConvert_v3_StagedKubernetesNetworkPolicy_To_projectcalico_StagedKubernetesNetworkPolicy(in, out, s)
}

func autoConvert_projectcalico_StagedKubernetesNetworkPolicy_To_v3_StagedKubernetesNetworkPolicy(in *projectcalico.StagedKubernetesNetworkPolicy, out *StagedKubernetesNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_StagedKubernetesNetworkPolicy_To_v3_StagedKubernetesNetworkPolicy is an autogenerated conversion function.
func Convert_projectcalico_StagedKubernetesNetworkPolicy_To_v3_StagedKubernetesNetworkPolicy(in *projectcalico.StagedKubernetesNetworkPolicy, out *StagedKubernetesNetworkPolicy, s conversion.Scope) error {
	return autoConvert_projectcalico_StagedKubernetesNetworkPolicy_To_v3_StagedKubernetesNetworkPolicy(in, out, s)
}

func autoConvert_v3_StagedKubernetesNetworkPolicyList_To_projectcalico_StagedKubernetesNetworkPolicyList(in *StagedKubernetesNetworkPolicyList, out *projectcalico.StagedKubernetesNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.StagedKubernetesNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_StagedKubernetesNetworkPolicyList_To_projectcalico_StagedKubernetesNetworkPolicyList is an autogenerated conversion function.
func Convert_v3_StagedKubernetesNetworkPolicyList_To_projectcalico_StagedKubernetesNetworkPolicyList(in *StagedKubernetesNetworkPolicyList, out *projectcalico.StagedKubernetesNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_v3_StagedKubernetesNetworkPolicyList_To_projectcalico_StagedKubernetesNetworkPolicyList(in, out, s)
}

func autoConvert_projectcalico_StagedKubernetesNetworkPolicyList_To_v3_StagedKubernetesNetworkPolicyList(in *projectcalico.StagedKubernetesNetworkPolicyList, out *StagedKubernetesNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]StagedKubernetesNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_StagedKubernetesNetworkPolicyList_To_v3_StagedKubernetesNetworkPolicyList is an autogenerated conversion function.
func Convert_projectcalico_StagedKubernetesNetworkPolicyList_To_v3_StagedKubernetesNetworkPolicyList(in *projectcalico.StagedKubernetesNetworkPolicyList, out *StagedKubernetesNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_projectcalico_StagedKubernetesNetworkPolicyList_To_v3_StagedKubernetesNetworkPolicyList(in, out, s)
}

func autoConvert_v3_StagedNetworkPolicy_To_projectcalico_StagedNetworkPolicy(in *StagedNetworkPolicy, out *projectcalico.StagedNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_StagedNetworkPolicy_To_projectcalico_StagedNetworkPolicy is an autogenerated conversion function.
func Convert_v3_StagedNetworkPolicy_To_projectcalico_StagedNetworkPolicy(in *StagedNetworkPolicy, out *projectcalico.StagedNetworkPolicy, s conversion.Scope) error {
	return autoConvert_v3_StagedNetworkPolicy_To_projectcalico_StagedNetworkPolicy(in, out, s)
}

func autoConvert_projectcalico_StagedNetworkPolicy_To_v3_StagedNetworkPolicy(in *projectcalico.StagedNetworkPolicy, out *StagedNetworkPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_StagedNetworkPolicy_To_v3_StagedNetworkPolicy is an autogenerated conversion function.
func Convert_projectcalico_StagedNetworkPolicy_To_v3_StagedNetworkPolicy(in *projectcalico.StagedNetworkPolicy, out *StagedNetworkPolicy, s conversion.Scope) error {
	return autoConvert_projectcalico_StagedNetworkPolicy_To_v3_StagedNetworkPolicy(in, out, s)
}

func autoConvert_v3_StagedNetworkPolicyList_To_projectcalico_StagedNetworkPolicyList(in *StagedNetworkPolicyList, out *projectcalico.StagedNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.StagedNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_StagedNetworkPolicyList_To_projectcalico_StagedNetworkPolicyList is an autogenerated conversion function.
func Convert_v3_StagedNetworkPolicyList_To_projectcalico_StagedNetworkPolicyList(in *StagedNetworkPolicyList, out *projectcalico.StagedNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_v3_StagedNetworkPolicyList_To_projectcalico_StagedNetworkPolicyList(in, out, s)
}

func autoConvert_projectcalico_StagedNetworkPolicyList_To_v3_StagedNetworkPolicyList(in *projectcalico.StagedNetworkPolicyList, out *StagedNetworkPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]StagedNetworkPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_StagedNetworkPolicyList_To_v3_StagedNetworkPolicyList is an autogenerated conversion function.
func Convert_projectcalico_StagedNetworkPolicyList_To_v3_StagedNetworkPolicyList(in *projectcalico.StagedNetworkPolicyList, out *StagedNetworkPolicyList, s conversion.Scope) error {
	return autoConvert_projectcalico_StagedNetworkPolicyList_To_v3_StagedNetworkPolicyList(in, out, s)
}

func autoConvert_v3_Tier_To_projectcalico_Tier(in *Tier, out *projectcalico.Tier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v3_Tier_To_projectcalico_Tier is an autogenerated conversion function.
func Convert_v3_Tier_To_projectcalico_Tier(in *Tier, out *projectcalico.Tier, s conversion.Scope) error {
	return autoConvert_v3_Tier_To_projectcalico_Tier(in, out, s)
}

func autoConvert_projectcalico_Tier_To_v3_Tier(in *projectcalico.Tier, out *Tier, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_projectcalico_Tier_To_v3_Tier is an autogenerated conversion function.
func Convert_projectcalico_Tier_To_v3_Tier(in *projectcalico.Tier, out *Tier, s conversion.Scope) error {
	return autoConvert_projectcalico_Tier_To_v3_Tier(in, out, s)
}

func autoConvert_v3_TierList_To_projectcalico_TierList(in *TierList, out *projectcalico.TierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]projectcalico.Tier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v3_TierList_To_projectcalico_TierList is an autogenerated conversion function.
func Convert_v3_TierList_To_projectcalico_TierList(in *TierList, out *projectcalico.TierList, s conversion.Scope) error {
	return autoConvert_v3_TierList_To_projectcalico_TierList(in, out, s)
}

func autoConvert_projectcalico_TierList_To_v3_TierList(in *projectcalico.TierList, out *TierList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Tier)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_projectcalico_TierList_To_v3_TierList is an autogenerated conversion function.
func Convert_projectcalico_TierList_To_v3_TierList(in *projectcalico.TierList, out *TierList, s conversion.Scope) error {
	return autoConvert_projectcalico_TierList_To_v3_TierList(in, out, s)
}
