// Code generated by mockery v2.3.0. DO NOT EDIT.

package capture

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockFileRetrieval is an autogenerated mock type for the FileRetrieval type
type MockFileRetrieval struct {
	mock.Mock
}

// OpenTarReader provides a mock function with given fields: clusterID, entryPoint
func (_m *MockFileRetrieval) OpenTarReader(clusterID string, entryPoint EntryPoint) (io.Reader, io.Reader, error) {
	ret := _m.Called(clusterID, entryPoint)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(string, EntryPoint) io.Reader); ok {
		r0 = rf(clusterID, entryPoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 io.Reader
	if rf, ok := ret.Get(1).(func(string, EntryPoint) io.Reader); ok {
		r1 = rf(clusterID, entryPoint)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.Reader)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, EntryPoint) error); ok {
		r2 = rf(clusterID, entryPoint)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
