{{ if .Values.installation.enabled }}
{{ $installSpec := omit .Values.installation "enabled" }}
{{ $_ := set $installSpec "imagePullSecrets" (include "tigera-operator.imagePullSecrets" . | fromYamlArray) }}
{{ $_ := set $installSpec "kubeletVolumePluginPath" .Values.kubeletVolumePluginPath }}

apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
{{ if .Values.techPreviewOptions.nodeApparmorPolicyName }}
  annotations:
    "tech-preview.operator.tigera.io/node-apparmor-profile": {{ .Values.techPreviewOptions.nodeApparmorPolicyName | quote}}
{{ end }}
spec:
{{ $installSpec | toYaml | indent 2 }}

{{ end }}

{{ if .Values.apiServer.enabled }}
{{ $apiServerSpec := omit .Values.apiServer "enabled" }}
---

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: tigera-secure
spec:
{{ $apiServerSpec | toYaml | indent 2 }}
{{ end }}

{{ if .Values.whisker.enabled }}
---

apiVersion: operator.tigera.io/v1
kind: Whisker
metadata:
  name: default
spec: {}
{{ end }}
