// Copyright (c) 2021-2022 Tigera, Inc. All rights reserved.

package capture

type EntryPod struct {
	// ContainerName represents the name of the container that will be
	// used as an entry point for the exec command
	ContainerName string
	// PodName represents the name of the pod that will be
	// used as an entry point for the exec command
	PodName string
	// PodNamespace represents the namespace of the pod that will be
	// used as an entry point for the exec command
	PodNamespace string
}

// EntryPoint is an internal structure used to create a "pod/exec" remote command in order
// to retrieve the pcap files generated by a packet capture
type EntryPoint struct {
	EntryPod

	// CaptureDirectory represents the directory internal to the entry point pod
	// that currently stores the pcap files
	CaptureDirectory string
	// CaptureNamespace represents the namespace of the packet capture
	CaptureNamespace string
	// CaptureName represents the name of the packet capture
	CaptureName string
}
