FROM scratch

COPY licenses /licenses/
COPY LICENSE /licenses/

LABEL maintainer "maintainers@projectcalico.org"

COPY bin/armv7 /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/install"]