// Copyright (c) 2018-2019 Tigera, Inc. All rights reserved.
package fv

import (
	"github.com/projectcalico/calico/calicoctl/calicoctl/resourcemgr"
	"github.com/projectcalico/calico/queryserver/pkg/querycache/client"
)

func summaryTestQueryData() []testQueryData {
	return []testQueryData{
		{
			"single node",
			[]resourcemgr.ResourceObject{node1},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          0,
				NumNetworkPolicies:                0,
				NumHostEndpoints:                  0,
				NumWorkloadEndpoints:              0,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        0,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          1,
				NumNodesWithNoEndpoints:           1,
				NumNodesWithNoWorkloadEndpoints:   1,
				NumNodesWithNoHostEndpoints:       1,
				NamespaceCounts:                   map[string]client.QueryClusterNamespaceCounts{},
			},
		},
		{
			"single wep",
			[]resourcemgr.ResourceObject{wep4_n2_ns1},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          0,
				NumNetworkPolicies:                0,
				NumHostEndpoints:                  0,
				NumWorkloadEndpoints:              1,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        0,
				NumUnprotectedWorkloadEndpoints:   1,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          1,
				NumNodesWithNoEndpoints:           0,
				NumNodesWithNoWorkloadEndpoints:   0,
				NumNodesWithNoHostEndpoints:       1,
				NamespaceCounts: map[string]client.QueryClusterNamespaceCounts{
					"namespace-1": {
						NumNetworkPolicies:              0,
						NumWorkloadEndpoints:            1,
						NumUnmatchedNetworkPolicies:     0,
						NumUnlabelledWorkloadEndpoints:  0,
						NumUnprotectedWorkloadEndpoints: 1,
						NumFailedWorkloadEndpoints:      0,
					},
				},
			},
		},
		{
			"single hep",
			[]resourcemgr.ResourceObject{hep3_n4},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          0,
				NumNetworkPolicies:                0,
				NumHostEndpoints:                  1,
				NumWorkloadEndpoints:              0,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        0,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       1,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          1,
				NumNodesWithNoEndpoints:           0,
				NumNodesWithNoWorkloadEndpoints:   1,
				NumNodesWithNoHostEndpoints:       0,
				NamespaceCounts:                   map[string]client.QueryClusterNamespaceCounts{},
			},
		},
		{
			"single tier + np",
			[]resourcemgr.ResourceObject{tier1, np2_t1_o2_ns2},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          0,
				NumNetworkPolicies:                1,
				NumHostEndpoints:                  0,
				NumWorkloadEndpoints:              0,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       1,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        0,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          0,
				NumNodesWithNoEndpoints:           0,
				NumNodesWithNoWorkloadEndpoints:   0,
				NumNodesWithNoHostEndpoints:       0,
				NamespaceCounts: map[string]client.QueryClusterNamespaceCounts{
					"namespace-2": {
						NumNetworkPolicies:              1,
						NumWorkloadEndpoints:            0,
						NumUnmatchedNetworkPolicies:     1,
						NumUnlabelledWorkloadEndpoints:  0,
						NumUnprotectedWorkloadEndpoints: 0,
						NumFailedWorkloadEndpoints:      0,
					},
				},
			},
		},
		{
			"single tier + gnp",
			[]resourcemgr.ResourceObject{tier1, gnp1_t1_o3},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          1,
				NumNetworkPolicies:                0,
				NumHostEndpoints:                  0,
				NumWorkloadEndpoints:              0,
				NumUnmatchedGlobalNetworkPolicies: 1,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        0,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          0,
				NumNodesWithNoEndpoints:           0,
				NumNodesWithNoWorkloadEndpoints:   0,
				NumNodesWithNoHostEndpoints:       0,
				NamespaceCounts:                   map[string]client.QueryClusterNamespaceCounts{},
			},
		},
		{
			"single tier + sgnp",
			[]resourcemgr.ResourceObject{tier1, sgnp1_t1_o3},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          1,
				NumNetworkPolicies:                0,
				NumHostEndpoints:                  0,
				NumWorkloadEndpoints:              0,
				NumUnmatchedGlobalNetworkPolicies: 1,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        0,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          0,
				NumNodesWithNoEndpoints:           0,
				NumNodesWithNoWorkloadEndpoints:   0,
				NumNodesWithNoHostEndpoints:       0,
				NamespaceCounts:                   map[string]client.QueryClusterNamespaceCounts{},
			},
		},
		{
			"multiple nodes, weps, heps, tier1 1 nps and 1 gnps - summary stats, endpoints on all nodes",
			[]resourcemgr.ResourceObject{
				node1, node2, hep2_n3, hep3_n4, hep1_n2, hep4_n4_unlabelled, wep4_n2_ns1, wep3_n1_ns2, wep1_n1_ns1,
				wep5_n3_ns2_unlabelled, tier1, gnp2_t1_o4, np2_t1_o2_ns2,
			},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          1,
				NumNetworkPolicies:                1,
				NumHostEndpoints:                  4,
				NumWorkloadEndpoints:              4,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    1,
				NumUnlabelledHostEndpoints:        1,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          4,
				NumNodesWithNoEndpoints:           0,
				NumNodesWithNoWorkloadEndpoints:   1,
				NumNodesWithNoHostEndpoints:       1,
				NamespaceCounts: map[string]client.QueryClusterNamespaceCounts{
					"namespace-1": {
						NumNetworkPolicies:              0,
						NumWorkloadEndpoints:            2,
						NumUnmatchedNetworkPolicies:     0,
						NumUnlabelledWorkloadEndpoints:  0,
						NumUnprotectedWorkloadEndpoints: 0,
						NumFailedWorkloadEndpoints:      0,
					},
					"namespace-2": {
						NumNetworkPolicies:              1,
						NumWorkloadEndpoints:            2,
						NumUnmatchedNetworkPolicies:     0,
						NumUnlabelledWorkloadEndpoints:  1,
						NumUnprotectedWorkloadEndpoints: 0,
						NumFailedWorkloadEndpoints:      0,
					},
				},
			},
		},
		{
			"multiple nodes, weps, no heps, tier1 2nps - summary stats",
			[]resourcemgr.ResourceObject{
				node1, node2, node3, node4, wep4_n2_ns1, wep3_n1_ns2, wep1_n1_ns1, wep5_n3_ns2_unlabelled,
				tier1, np2_t1_o2_ns2, np1_t1_o1_ns1,
			},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          0,
				NumNetworkPolicies:                2,
				NumHostEndpoints:                  0,
				NumWorkloadEndpoints:              4,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       1,
				NumUnlabelledWorkloadEndpoints:    1,
				NumUnlabelledHostEndpoints:        0,
				NumUnprotectedWorkloadEndpoints:   2,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          4,
				NumNodesWithNoEndpoints:           1,
				NumNodesWithNoWorkloadEndpoints:   1,
				NumNodesWithNoHostEndpoints:       4,
				NamespaceCounts: map[string]client.QueryClusterNamespaceCounts{
					"namespace-1": {
						NumNetworkPolicies:              1,
						NumWorkloadEndpoints:            2,
						NumUnmatchedNetworkPolicies:     1,
						NumUnlabelledWorkloadEndpoints:  0,
						NumUnprotectedWorkloadEndpoints: 2,
						NumFailedWorkloadEndpoints:      0,
					},
					"namespace-2": {
						NumNetworkPolicies:              1,
						NumWorkloadEndpoints:            2,
						NumUnmatchedNetworkPolicies:     0,
						NumUnlabelledWorkloadEndpoints:  1,
						NumUnprotectedWorkloadEndpoints: 0,
						NumFailedWorkloadEndpoints:      0,
					},
				},
			},
		},
		{
			"multiple nodes, heps, no weps, tier1 2 gnps - summary stats",
			[]resourcemgr.ResourceObject{
				node1, node2, node3, node4, hep2_n3, hep3_n4, hep1_n2, hep4_n4_unlabelled,
				tier1, gnp1_t1_o3, gnp2_t1_o4,
			},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          2,
				NumNetworkPolicies:                0,
				NumHostEndpoints:                  4,
				NumWorkloadEndpoints:              0,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        1,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          4,
				NumNodesWithNoEndpoints:           1,
				NumNodesWithNoWorkloadEndpoints:   4,
				NumNodesWithNoHostEndpoints:       1,
				NamespaceCounts:                   map[string]client.QueryClusterNamespaceCounts{},
			},
		},
		{
			"multiple nodes, heps, no weps, tier1 2 sgnps - summary stats",
			[]resourcemgr.ResourceObject{
				node1, node2, node3, node4, hep2_n3, hep3_n4, hep1_n2, hep4_n4_unlabelled,
				tier1, sgnp1_t1_o3, sgnp2_t1_o4,
			},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NumGlobalNetworkPolicies:          2,
				NumNetworkPolicies:                0,
				NumHostEndpoints:                  4,
				NumWorkloadEndpoints:              0,
				NumUnmatchedGlobalNetworkPolicies: 0,
				NumUnmatchedNetworkPolicies:       0,
				NumUnlabelledWorkloadEndpoints:    0,
				NumUnlabelledHostEndpoints:        1,
				NumUnprotectedWorkloadEndpoints:   0,
				NumUnprotectedHostEndpoints:       0,
				NumFailedWorkloadEndpoints:        0,
				NumNodes:                          4,
				NumNodesWithNoEndpoints:           1,
				NumNodesWithNoWorkloadEndpoints:   4,
				NumNodesWithNoHostEndpoints:       1,
				NamespaceCounts:                   map[string]client.QueryClusterNamespaceCounts{},
			},
		},
		{
			"reset by removing all resources",
			[]resourcemgr.ResourceObject{},
			client.QueryClusterReq{},
			&client.QueryClusterResp{
				NamespaceCounts: map[string]client.QueryClusterNamespaceCounts{},
			},
		},
	}
}
