// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/authorization/v1"
	user "k8s.io/apiserver/pkg/authentication/user"
)

// RBACAuthorizer is an autogenerated mock type for the RBACAuthorizer type
type RBACAuthorizer struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: usr, resources, nonResources
func (_m *RBACAuthorizer) Authorize(usr user.Info, resources *v1.ResourceAttributes, nonResources *v1.NonResourceAttributes) (bool, error) {
	ret := _m.Called(usr, resources, nonResources)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) bool); ok {
		r0 = rf(usr, resources, nonResources)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) error); ok {
		r1 = rf(usr, resources, nonResources)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRBACAuthorizer interface {
	mock.TestingT
	Cleanup(func())
}

// NewRBACAuthorizer creates a new instance of RBACAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRBACAuthorizer(t mockConstructorTestingTNewRBACAuthorizer) *RBACAuthorizer {
	mock := &RBACAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
