// Code generated by mockery v2.45.1. DO NOT EDIT.

package elasticsearch

import mock "github.com/stretchr/testify/mock"

// MockClientBuilder is an autogenerated mock type for the ClientBuilder type
type MockClientBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *MockClientBuilder) Build() (Client, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 Client
	var r1 error
	if rf, ok := ret.Get(0).(func() (Client, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Client)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClientBuilder creates a new instance of MockClientBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientBuilder {
	mock := &MockClientBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
