FROM ubuntu:20.04 as ubuntu

# Get the latest trusted CA bundle.
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates -f

FROM scratch
COPY --from=ubuntu /etc/ssl/certs /etc/ssl/certs
ADD bin/controller-amd64 /controller
WORKDIR /
ENTRYPOINT ["/controller"]
