ARG UBI_IMAGE

FROM ${UBI_IMAGE} as builder

RUN microdnf upgrade

FROM scratch

ADD bin/{{ lower .Name }}-amd64 /usr/bin/{{ lower .Name }}

USER 10001:10001

# Now define the command-line call to start your application
ENTRYPOINT ["/usr/bin/{{ lower .Name }}"]
