FROM ubuntu:20.04 as ubuntu
RUN apt-get update && apt-get install -y ca-certificates

RUN rm -rf /tmp
RUN mkdir /tmp

FROM scratch

COPY --from=ubuntu /etc/passwd /etc/passwd
COPY --from=ubuntu /etc/ssl/certs /etc/ssl/certs
COPY --from=ubuntu /tmp /tmp

ADD bin/controller-amd64 /controller
ADD bin/healthz-amd64 /healthz

WORKDIR /

USER 10001

ENTRYPOINT ["/controller"]
