// Code generated by mockery v2.3.0. DO NOT EDIT.

package elastic

import (
	context "context"

	apisv3 "github.com/projectcalico/libcalico-go/lib/apis/v3"

	mock "github.com/stretchr/testify/mock"

	v3 "github.com/projectcalico/apiserver/pkg/apis/projectcalico/v3"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// DeleteElasticWatchers provides a mock function with given fields: _a0
func (_m *MockService) DeleteElasticWatchers(_a0 context.Context) {
	_m.Called(_a0)
}

// ExecuteAlert provides a mock function with given fields: _a0
func (_m *MockService) ExecuteAlert(_a0 *v3.GlobalAlert) apisv3.GlobalAlertStatus {
	ret := _m.Called(_a0)

	var r0 apisv3.GlobalAlertStatus
	if rf, ok := ret.Get(0).(func(*v3.GlobalAlert) apisv3.GlobalAlertStatus); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(apisv3.GlobalAlertStatus)
	}

	return r0
}
