#!/bin/bash

cat <<EOF

Running calicoq FV tests with ${CALICOQ=calicoq}

EOF

passed=0
failed=0

function run_test {
    expected_result=$1
    shift
    echo ------------------------------------------------------
    echo TEST: "$@"
    echo
    eval "$@"
    result=$?
    echo
    if test $result -eq $expected_result; then
	echo TEST: PASSED
	let 'passed++'
    else
	echo TEST: FAILED \($result\)
	let 'failed++'
    fi
    echo ------------------------------------------------------
    echo
}

function summarise_test {
    echo ------------------------------------------------------
    echo FV TEST SUMMARY: $passed PASSED, $failed FAILED
    echo ------------------------------------------------------
    echo
}

run_test 0 ${CALICOQ} -h

run_test 0 ${CALICOQ} --help

run_test 0 ${CALICOQ} --version

run_test 0 ${CALICOQ} version

run_test 0 ${CALICOQ} endpoint -h

run_test 0 ${CALICOQ} eval -h

run_test 0 ${CALICOQ} host -h

run_test 0 ${CALICOQ} policy -h

run_test 0 ${CALICOQ} version -h

run_test 1 ${CALICOQ}

run_test 1 ${CALICOQ} non-existent-command

run_test 0 ${CALICOQ} -d version

run_test 0 ${CALICOQ} --debug version

summarise_test

exit $failed
