// Copyright (c) 2021 Tigera, Inc. All rights reserved.

package capture

// EntryPoint is an internal structure used to create a "pod/exec" remote command in order
// to retrieve the pcap files generated by a packet capture
type EntryPoint struct {
	// PodName represent the name of the pod that will be
	// used as an entry point for the exec command
	PodName string
	// PodNamespace represent the namespace of the pod that will be
	// used as an entry point for the exec command
	PodNamespace string
	// CaptureDirectory represent the directory internal to the entry point pod
	// that currently stores the pcap files
	CaptureDirectory string
	// CaptureNamespace represent the namespace of the packet capture
	CaptureNamespace string
	// CaptureName represent the name of the packet capture
	CaptureName string
}
