// Code generated by mockery v2.3.0. DO NOT EDIT.

package syncer

import mock "github.com/stretchr/testify/mock"

// MockSyncerCallbacks is an autogenerated mock type for the SyncerCallbacks type
type MockSyncerCallbacks struct {
	mock.Mock
}

// OnStatusUpdate provides a mock function with given fields: status
func (_m *MockSyncerCallbacks) OnStatusUpdate(status StatusUpdate) {
	_m.Called(status)
}

// OnUpdates provides a mock function with given fields: updates
func (_m *MockSyncerCallbacks) OnUpdates(updates []Update) {
	_m.Called(updates)
}
