#!/bin/bash

awk '

BEGIN {
  print "digraph {"
  print "  rankdir=LR;"
  print "  node [style=rounded, shape=box, fontname=Courier, fontsize=16];"
}

{
  printf "  \"%s\" -> \"%s\";\n", $1, $2
}

END {
  print "}"
}

' "$@"


