#!/bin/bash

cat <<EOF

Running calicoq ST tests with ${CALICOQ=calicoq}

EOF

passed=0
failed=0

function summarise_test {
    echo ------------------------------------------------------
    echo ST TEST SUMMARY: $passed PASSED, $failed FAILED
    echo ------------------------------------------------------
    echo
}

# Get a calicoctl.
cd st
if ! test -x calicoctl; then
    wget https://github.com/projectcalico/calicoctl/releases/download/v2.0.0-alpha1/calicoctl
    chmod a+x calicoctl
fi
CALICOCTL=`pwd`/calicoctl

# Check there isn't already a calicoq-etcd container.
docker rm -f calicoq-etcd 2>/dev/null

# Run each test case in turn.
cd test-cases
for c in `ls`; do

    cd ${c}

    echo ------------------------------------------------------
    echo TEST: ${c}

    # Establish settings for this test case directory.
    ETCD_PORT=2379
    USE_CFG_FILE=false
    CFG_FILE_INSERT=
    if [ -f config.sh ]; then
	source config.sh
	echo ETCD_PORT=${ETCD_PORT}
	echo USE_CFG_FILE=${USE_CFG_FILE}
	echo CFG_FILE_INSERT=${CFG_FILE_INSERT}
    fi

    # Run etcd.
    docker run --detach --name calicoq-etcd \
       quay.io/coreos/etcd \
       etcd \
       --advertise-client-urls "http://127.0.0.1:${ETCD_PORT}" \
       --listen-client-urls "http://0.0.0.0:${ETCD_PORT}"
    etcd_ip=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' calicoq-etcd)
    export ETCD_ENDPOINTS=http://${etcd_ip}:${ETCD_PORT}
    export DATASTORE_TYPE=etcdv3

    # Apply the resources for the test case.
    ${CALICOCTL} apply -f apply.yaml

    # Mark the DB as ready.
    while ! curl ${ETCD_ENDPOINTS}/v2/keys/calico/v1/Ready -XPUT -d value="true"; do
	# TODO (mattl): Need to fix this so that adjusting this time does not affect tests
	# Currently containerized tests will not pass in Jenkins most of the time with 2 set
	sleep 4
    done

    # Create config file, if wanted.
    if ${USE_CFG_FILE}; then
	tee calicoq.cfg <<EOF
apiVersion: projectcalico.org/v2
${CFG_FILE_INSERT}kind: CalicoAPIConfig
metadata:
spec:
  datastoreType: "${DATASTORE_TYPE}"
  etcdEndpoints: "${ETCD_ENDPOINTS}"
EOF
	unset ETCD_ENDPOINTS DATASTORE_TYPE
    fi

    # Check all the expected outputs.
    for expected in `ls *.expected`; do
	actual=$(basename ${expected} .expected).actual
	stderr=$(basename ${expected} .expected).stderr
	head -2 ${expected} > ${actual}
	eval '${CALICOQ} `head -1 ${expected}`' >> ${actual} 2> ${stderr}
	stderr_lines=`wc -l ${stderr} | awk '{print $1;}'`
	if test "$stderr_lines" -ne 0; then
	    echo >> ${actual}
	    echo "Plus $stderr_lines lines on stderr" >> ${actual}
	fi
	if diff -u ${expected} ${actual}; then
	    echo TEST: ${c}/${expected}: PASSED
	    let 'passed++'
	else
	    echo TEST: ${c}/${expected}: FAILED
	    let 'failed++'
	fi
	rm ${actual} ${stderr}
    done

    docker rm -f calicoq-etcd >/dev/null
    rm -f calicoq.cfg

    echo ------------------------------------------------------
    echo

    cd ..

done

summarise_test

exit $failed
