# Copyright (c) 2023-2025 Tigera, Inc. All rights reserved.

ARG CALICO_BASE

FROM scratch AS source

ARG TARGETARCH

COPY bin/{{ lower .Name }}-${TARGETARCH} /usr/bin/{{ lower .Name }}

FROM ${CALICO_BASE}

COPY --from=source / /

USER 10001:10001

# Now define the command-line call to start your application
ENTRYPOINT ["/usr/bin/{{ lower .Name }}"]
