// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"context"

	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	scheme "github.com/tigera/api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AuthenticationReviewsGetter has a method to return a AuthenticationReviewInterface.
// A group's client should implement this interface.
type AuthenticationReviewsGetter interface {
	AuthenticationReviews() AuthenticationReviewInterface
}

// AuthenticationReviewInterface has methods to work with AuthenticationReview resources.
type AuthenticationReviewInterface interface {
	Create(ctx context.Context, authenticationReview *v3.AuthenticationReview, opts v1.CreateOptions) (*v3.AuthenticationReview, error)
	Update(ctx context.Context, authenticationReview *v3.AuthenticationReview, opts v1.UpdateOptions) (*v3.AuthenticationReview, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, authenticationReview *v3.AuthenticationReview, opts v1.UpdateOptions) (*v3.AuthenticationReview, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v3.AuthenticationReview, error)
	List(ctx context.Context, opts v1.ListOptions) (*v3.AuthenticationReviewList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.AuthenticationReview, err error)
	AuthenticationReviewExpansion
}

// authenticationReviews implements AuthenticationReviewInterface
type authenticationReviews struct {
	*gentype.ClientWithList[*v3.AuthenticationReview, *v3.AuthenticationReviewList]
}

// newAuthenticationReviews returns a AuthenticationReviews
func newAuthenticationReviews(c *ProjectcalicoV3Client) *authenticationReviews {
	return &authenticationReviews{
		gentype.NewClientWithList[*v3.AuthenticationReview, *v3.AuthenticationReviewList](
			"authenticationreviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v3.AuthenticationReview { return &v3.AuthenticationReview{} },
			func() *v3.AuthenticationReviewList { return &v3.AuthenticationReviewList{} }),
	}
}
