// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"context"

	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	scheme "github.com/tigera/api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ManagedClustersGetter has a method to return a ManagedClusterInterface.
// A group's client should implement this interface.
type ManagedClustersGetter interface {
	ManagedClusters() ManagedClusterInterface
}

// ManagedClusterInterface has methods to work with ManagedCluster resources.
type ManagedClusterInterface interface {
	Create(ctx context.Context, managedCluster *v3.ManagedCluster, opts v1.CreateOptions) (*v3.ManagedCluster, error)
	Update(ctx context.Context, managedCluster *v3.ManagedCluster, opts v1.UpdateOptions) (*v3.ManagedCluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, managedCluster *v3.ManagedCluster, opts v1.UpdateOptions) (*v3.ManagedCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v3.ManagedCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v3.ManagedClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.ManagedCluster, err error)
	ManagedClusterExpansion
}

// managedClusters implements ManagedClusterInterface
type managedClusters struct {
	*gentype.ClientWithList[*v3.ManagedCluster, *v3.ManagedClusterList]
}

// newManagedClusters returns a ManagedClusters
func newManagedClusters(c *ProjectcalicoV3Client) *managedClusters {
	return &managedClusters{
		gentype.NewClientWithList[*v3.ManagedCluster, *v3.ManagedClusterList](
			"managedclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v3.ManagedCluster { return &v3.ManagedCluster{} },
			func() *v3.ManagedClusterList { return &v3.ManagedClusterList{} }),
	}
}
