# This section includes base Calico Enterprise installation configuration.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Install Calico Enterprise
  variant: TigeraSecureEnterprise

  # Define how the cluster will be managed. 
  # Valid values for this field are: Standalone, Management, Managed.
  # A Standalone cluster is a fully self-contained installation of Calico Enterprise. 
  # A Management cluster can manage one or more other Calico Enterprise clusters that connect to it. 
  # A Managed cluster must connect to a Management cluster in order to operate correctly. 
  clusterManagementType: Standalone

  # List of image pull secrets to use when installing images from a container registry.
  # If specified, secrets must be created in the `tigera-operator` namespace.
  imagePullSecrets:
    - name: tigera-pull-secret

  # Optionally, a custom registry to use for pulling images.
  # registry: <my-registry>

{%- if include.kubernetesProvider %}

  # Enables provider-specific settings required for compatibility.
  kubernetesProvider: {{include.kubernetesProvider}}
{%- endif %}

---

# This section configures the Tigera web manager.
# Remove this section for a Managed cluster.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.Manager
apiVersion: operator.tigera.io/v1
kind: Manager
metadata:
  name: tigera-secure
spec:
  # Authentication configuration for accessing the Tigera manager.
  # Default is to use token-based authentication.
  auth:
    type: Token

---

# This section installs and configures the Calico Enterprise API server.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: tigera-secure

---

# This section installs and configures Calico Enterprise compliance functionality.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.Compliance
apiVersion: operator.tigera.io/v1
kind: Compliance
metadata:
  name: tigera-secure

---

# This section installs and configures Calico Enterprise intrusion detection functionality.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.IntrusionDetection
apiVersion: operator.tigera.io/v1
kind: IntrusionDetection
metadata:
  name: tigera-secure

---

# This section configures the Elasticsearch cluster used by Calico Enterprise.
# Remove this section for a Managed cluster.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.LogStorage
apiVersion: operator.tigera.io/v1
kind: LogStorage
metadata:
  name: tigera-secure
spec:
  nodes:
    count: 1
    resourceRequirements:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 250m
        memory: 4Gi
        storage: 10Gi

---

# This section configures collection of Tigera flow, DNS, and audit logs.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.LogCollector
apiVersion: operator.tigera.io/v1
kind: LogCollector
metadata:
  name: tigera-secure

---
