// Copyright (c) 2019 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

// GlobalNetworkPolicyListerExpansion allows custom methods to be added to
// GlobalNetworkPolicyLister.
type GlobalNetworkPolicyListerExpansion interface{}

// GlobalNetworkSetListerExpansion allows custom methods to be added to
// GlobalNetworkSetLister.
type GlobalNetworkSetListerExpansion interface{}

// GlobalReportListerExpansion allows custom methods to be added to
// GlobalReportLister.
type GlobalReportListerExpansion interface{}

// GlobalReportTypeListerExpansion allows custom methods to be added to
// GlobalReportTypeLister.
type GlobalReportTypeListerExpansion interface{}

// GlobalThreatFeedListerExpansion allows custom methods to be added to
// GlobalThreatFeedLister.
type GlobalThreatFeedListerExpansion interface{}

// HostEndpointListerExpansion allows custom methods to be added to
// HostEndpointLister.
type HostEndpointListerExpansion interface{}

// IPPoolListerExpansion allows custom methods to be added to
// IPPoolLister.
type IPPoolListerExpansion interface{}

// LicenseKeyListerExpansion allows custom methods to be added to
// LicenseKeyLister.
type LicenseKeyListerExpansion interface{}

// NetworkPolicyListerExpansion allows custom methods to be added to
// NetworkPolicyLister.
type NetworkPolicyListerExpansion interface{}

// NetworkPolicyNamespaceListerExpansion allows custom methods to be added to
// NetworkPolicyNamespaceLister.
type NetworkPolicyNamespaceListerExpansion interface{}

// TierListerExpansion allows custom methods to be added to
// TierLister.
type TierListerExpansion interface{}
