// Copyright (c) 2018 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

// GlobalNetworkPolicyListerExpansion allows custom methods to be added to
// GlobalNetworkPolicyLister.
type GlobalNetworkPolicyListerExpansion interface{}

// GlobalNetworkSetListerExpansion allows custom methods to be added to
// GlobalNetworkSetLister.
type GlobalNetworkSetListerExpansion interface{}

// NetworkPolicyListerExpansion allows custom methods to be added to
// NetworkPolicyLister.
type NetworkPolicyListerExpansion interface{}

// NetworkPolicyNamespaceListerExpansion allows custom methods to be added to
// NetworkPolicyNamespaceLister.
type NetworkPolicyNamespaceListerExpansion interface{}

// TierListerExpansion allows custom methods to be added to
// TierLister.
type TierListerExpansion interface{}
