// Copyright (c) 2021 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v3 "github.com/projectcalico/apiserver/pkg/apis/projectcalico/v3"
)

// GlobalAlertLister helps list GlobalAlerts.
// All objects returned here must be treated as read-only.
type GlobalAlertLister interface {
	// List lists all GlobalAlerts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v3.GlobalAlert, err error)
	// Get retrieves the GlobalAlert from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v3.GlobalAlert, error)
	GlobalAlertListerExpansion
}

// globalAlertLister implements the GlobalAlertLister interface.
type globalAlertLister struct {
	indexer cache.Indexer
}

// NewGlobalAlertLister returns a new GlobalAlertLister.
func NewGlobalAlertLister(indexer cache.Indexer) GlobalAlertLister {
	return &globalAlertLister{indexer: indexer}
}

// List lists all GlobalAlerts in the indexer.
func (s *globalAlertLister) List(selector labels.Selector) (ret []*v3.GlobalAlert, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v3.GlobalAlert))
	})
	return ret, err
}

// Get retrieves the GlobalAlert from the index for a given name.
func (s *globalAlertLister) Get(name string) (*v3.GlobalAlert, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v3.Resource("globalalert"), name)
	}
	return obj.(*v3.GlobalAlert), nil
}
