#!/usr/bin/env bash

# Copyright (c) 2021 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

#TODO re-enable windows FV with new infra


FV_DIR="/home/semaphore/calico-private/process/testing/winfv-felix"

pushd ${FV_DIR}
# Prepare local files
cp ~/.docker/config.json docker_auth.json
cp ~/secrets/docker_cfg.json docker_cfg.json

cp -r ~/$SEMAPHORE_GIT_DIR/libcalico-go/config/crd ./infra/ee/crd
cp ~/secrets/license.yaml ./infra/ee/license.yaml
EXIT_CODE=0
if [[ $FV_PROVISIONER == "capz" ]]; then
  export KUBE_VERSION="$K8S_VERSION"
  mkdir -p /home/semaphore/report
  /bin/bash -x ./setup-fv-capz.sh -q | tee /home/semaphore/report/fv-capz.log
  if [[ ${PIPESTATUS[0]} != 0 ]]; then
    EXIT_CODE=${PIPESTATUS[0]}
  fi
  compgen -G ./report/*.log > /dev/null && cp ./report/*.log /home/semaphore/report
fi
ls -ltr ./report
mkdir /home/semaphore/fv.log
# check if *.log glob contains any files so that mv doesn't fail
compgen -G /home/semaphore/report/*.log > /dev/null && mv /home/semaphore/report/*.log /home/semaphore/fv.log

# Stop for debug
echo "Check for pause file..."
while [ -f /home/semaphore/pause-for-debug ];
do
    echo "#"
    sleep 30
done

# Print relevant snippets from logs
log_regexps='(?<!Decode)Failure|SUCCESS|FV-TEST-START'
compgen -G /home/semaphore/fv.log/*.log > /dev/null && \
for log_file in /home/semaphore/fv.log/*.log; do
    prefix="[$(basename ${log_file})]"
    cat ${log_file} | iconv -f UTF-16 -t UTF-8 | sed 's/\r$//g' | grep --line-buffered --perl ${log_regexps} -B 2 -A 15 | sed 's/.*/'"${prefix}"' &/g'
done;

# Search for error code file
if [[ -f /home/semaphore/calico-private/process/testing/winfv-felix/report/error-codes || $EXIT_CODE != 0 ]];
then
    echo "Windows FV returned error(s)."
    exit 1
fi

echo "Run Windows FV is done."
