FROM ubuntu:20.04 as ubuntu
RUN apt-get update && apt-get install -y ca-certificates

FROM scratch

COPY --from=ubuntu /etc/ssl/certs /etc/ssl/certs
COPY --from=ubuntu /etc/passwd /etc/passwd

# Ensure the /tmp directory exists in case glog wants to write to it
COPY tmp.txt /tmp/tmp.txt
ADD bin/controller-amd64 /controller
ADD bin/healthz-amd64 /healthz
WORKDIR /

ENTRYPOINT ["/controller"]
