#FROM ubuntu:18.04 as ubuntu
#FROM gcr.io/tigera-security-research/honeypod-snort as snort
FROM golang:1.14-buster
#FROM ubuntu:18.04
RUN apt update && apt-get install -y ca-certificates 

#COPY --from=snort . /
#FROM scratch

#COPY --from=ubuntu /etc/ssl/certs /etc/ssl/certs
# Ensure the /tmp directory exists in case glog wants to write to it
#COPY tmp.txt /tmp/tmp.txt
#ADD bin/controller /controller
#ADD bin/healthz-amd64 /healthz

#ENV GOCACHE=controller_prod
#COPY controller_prod /go/src
#WORKDIR /go/src
#RUN go build controller_prod/cmd/controller/controller.go


COPY bin/controller-amd64 /controller

WORKDIR /
#RUN add-apt-repository ppa:gophers/archive
#RUN apt update
#RUN apt install -y snort

USER root
#USER 999
#ENTRYPOINT ["/controller"]
ENTRYPOINT ["/bin/sh", "-c", "while true;do sleep 5; done"]

