// Code generated by mockery v2.3.0. DO NOT EDIT.

package dpiupdater

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/projectcalico/calico/libcalico-go/lib/backend/model"
)

// MockDPIStatusUpdater is an autogenerated mock type for the DPIStatusUpdater type
type MockDPIStatusUpdater struct {
	mock.Mock
}

// UpdateStatus provides a mock function with given fields: ctx, dpiKey, isActive
func (_m *MockDPIStatusUpdater) UpdateStatus(ctx context.Context, dpiKey model.ResourceKey, isActive bool) {
	_m.Called(ctx, dpiKey, isActive)
}

// UpdateStatusWithError provides a mock function with given fields: ctx, dpiKey, isActive, errMsg
func (_m *MockDPIStatusUpdater) UpdateStatusWithError(ctx context.Context, dpiKey model.ResourceKey, isActive bool, errMsg string) {
	_m.Called(ctx, dpiKey, isActive, errMsg)
}
