// Code generated by mockery v2.14.0. DO NOT EDIT.

package dpiupdater

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/projectcalico/calico/libcalico-go/lib/backend/model"
)

// MockDPIStatusUpdater is an autogenerated mock type for the DPIStatusUpdater type
type MockDPIStatusUpdater struct {
	mock.Mock
}

// UpdateStatus provides a mock function with given fields: ctx, dpiKey, isActive
func (_m *MockDPIStatusUpdater) UpdateStatus(ctx context.Context, dpiKey model.ResourceKey, isActive bool) {
	_m.Called(ctx, dpiKey, isActive)
}

// UpdateStatusWithError provides a mock function with given fields: ctx, dpiKey, isActive, errMsg
func (_m *MockDPIStatusUpdater) UpdateStatusWithError(ctx context.Context, dpiKey model.ResourceKey, isActive bool, errMsg string) {
	_m.Called(ctx, dpiKey, isActive, errMsg)
}

type mockConstructorTestingTNewMockDPIStatusUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDPIStatusUpdater creates a new instance of MockDPIStatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDPIStatusUpdater(t mockConstructorTestingTNewMockDPIStatusUpdater) *MockDPIStatusUpdater {
	mock := &MockDPIStatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
