// Code generated by mockery v2.3.0. DO NOT EDIT.

package tunnel

import mock "github.com/stretchr/testify/mock"

// MockDialer is an autogenerated mock type for the Dialer type
type MockDialer struct {
	mock.Mock
}

// Dial provides a mock function with given fields:
func (_m *MockDialer) Dial() (*Tunnel, error) {
	ret := _m.Called()

	var r0 *Tunnel
	if rf, ok := ret.Get(0).(func() *Tunnel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Tunnel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
