FROM amd64/python:3-alpine
ARG version=dirty

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY install.py ./
COPY data ./data
COPY config.yaml ./
RUN echo $version > ./version.txt

ENTRYPOINT ["python", "install.py"]