// Code generated by mockery v2.46.3. DO NOT EDIT.

package api

import (
	context "context"

	elastic "github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// MockAuditBackend is an autogenerated mock type for the AuditBackend type
type MockAuditBackend struct {
	mock.Mock
}

// Aggregations provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAuditBackend) Aggregations(_a0 context.Context, _a1 ClusterInfo, _a2 *v1.AuditLogAggregationParams) (*elastic.Aggregations, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Aggregations")
	}

	var r0 *elastic.Aggregations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogAggregationParams) (*elastic.Aggregations, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogAggregationParams) *elastic.Aggregations); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Aggregations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.AuditLogAggregationParams) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockAuditBackend) Create(_a0 context.Context, _a1 v1.AuditLogType, _a2 ClusterInfo, _a3 []v1.AuditLog) (*v1.BulkResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.AuditLogType, ClusterInfo, []v1.AuditLog) (*v1.BulkResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.AuditLogType, ClusterInfo, []v1.AuditLog) *v1.BulkResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.AuditLogType, ClusterInfo, []v1.AuditLog) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAuditBackend) List(_a0 context.Context, _a1 ClusterInfo, _a2 *v1.AuditLogParams) (*v1.List[v1.AuditLog], error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.AuditLog]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogParams) (*v1.List[v1.AuditLog], error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogParams) *v1.List[v1.AuditLog]); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.AuditLog])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.AuditLogParams) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAuditBackend creates a new instance of MockAuditBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditBackend {
	mock := &MockAuditBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
