// Code generated by mockery v2.14.0. DO NOT EDIT.

package api

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// MockFlowLogBackend is an autogenerated mock type for the FlowLogBackend type
type MockFlowLogBackend struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFlowLogBackend) Create(_a0 context.Context, _a1 ClusterInfo, _a2 []v1.FlowLog) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.FlowLog) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Initialize provides a mock function with given fields: _a0
func (_m *MockFlowLogBackend) Initialize(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockFlowLogBackend interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFlowLogBackend creates a new instance of MockFlowLogBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFlowLogBackend(t mockConstructorTestingTNewMockFlowLogBackend) *MockFlowLogBackend {
	mock := &MockFlowLogBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
