// Code generated by mockery v2.46.3. DO NOT EDIT.

package api

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// MockProcessBackend is an autogenerated mock type for the ProcessBackend type
type MockProcessBackend struct {
	mock.Mock
}

// List provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockProcessBackend) List(_a0 context.Context, _a1 ClusterInfo, _a2 *v1.ProcessParams) (*v1.List[v1.ProcessInfo], error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.ProcessInfo]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.ProcessParams) (*v1.List[v1.ProcessInfo], error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.ProcessParams) *v1.List[v1.ProcessInfo]); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.ProcessInfo])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.ProcessParams) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockProcessBackend creates a new instance of MockProcessBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessBackend {
	mock := &MockProcessBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
