apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tigera-internal-1 
  namespace: tigera-internal
spec:
  selector:
    matchLabels:
      app: tigera-internal-1
  template:
    metadata:
      labels:
        app: tigera-internal-1
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: tigera-internal-1
        image: quay.io/tigera/honeypod:v2.7.0
---
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.ip.enum
spec:
  description: "Alerts on Honeypod accessed via IP enumeration"
  summary: "[Honeypod] Pod subnet IP enumeration by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.ip.enum
spec:
  description: "[Honeypod] Pod subnet IP enumeration by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: honeypod.port.scan
spec:
  description: "Alerts on Honeypod accessed via port scan"
  summary: "[Honeypod] Pod subnet port scan by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
  metric: count
  condition: gte
  threshold: 4
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: honeypod.port.scan
spec:
  description: "[Honeypod] Pod subnet port scan by ${source_namespace}/${source_name_aggr}"
  severity: 100
  dataSet: flows
  query: 'dest_namespace="tigera-internal" AND "dest_labels.labels"="app=tigera-internal-1"'
  aggregateBy: [source_namespace, source_name_aggr]
  metric: count
  condition: gte
  threshold: 4
---
