// Copyright (c) 2024 Tigera, Inc. All rights reserved.

package helpers

import (
	lsApi "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

const (
	notAvailable = "n/a"
)

var (
	naIntBlank = int64(0)
	naMapBlank = []string{notAvailable}
	naStrBlank = notAvailable
)

// Events generated by GlobalAlerts don't contain all the data expected
// to be present. This function simply fills in the blanks required to
// generate webhook payloads for such cases.
func FillInEventBlanks(event *lsApi.Event) {
	if event.DestIP == nil {
		event.DestIP = &naStrBlank
	}
	if event.DestPort == nil {
		event.DestPort = &naIntBlank
	}
	if event.SourceIP == nil {
		event.SourceIP = &naStrBlank
	}
	if event.SourcePort == nil {
		event.SourcePort = &naIntBlank
	}
	if event.MitreIDs == nil {
		event.MitreIDs = &naMapBlank
	}
	if event.Mitigations == nil {
		event.Mitigations = &naMapBlank
	}
	if event.AttackVector == "" {
		event.AttackVector = notAvailable
	}
	if event.MitreTactic == "" {
		event.MitreTactic = notAvailable
	}
}
