// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// BFDConfigurationLister helps list BFDConfigurations.
// All objects returned here must be treated as read-only.
type BFDConfigurationLister interface {
	// List lists all BFDConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v3.BFDConfiguration, err error)
	// Get retrieves the BFDConfiguration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v3.BFDConfiguration, error)
	BFDConfigurationListerExpansion
}

// bFDConfigurationLister implements the BFDConfigurationLister interface.
type bFDConfigurationLister struct {
	listers.ResourceIndexer[*v3.BFDConfiguration]
}

// NewBFDConfigurationLister returns a new BFDConfigurationLister.
func NewBFDConfigurationLister(indexer cache.Indexer) BFDConfigurationLister {
	return &bFDConfigurationLister{listers.New[*v3.BFDConfiguration](indexer, v3.Resource("bfdconfiguration"))}
}
