kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: policy-reader
rules:
- apiGroups: ["projectcalico.org"] # "" indicates the core API group
  resources: ["policies"]
  verbs: ["get", "watch", "list"]
---
# This role binding allows "jane" to read policies in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-policies
  namespace: default
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: policy-reader
  apiGroup: rbac.authorization.k8s.io
