// Copyright (c) 2021 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package internalversion

type AuthenticationReviewExpansion interface{}

type AuthorizationReviewExpansion interface{}

type BGPConfigurationExpansion interface{}

type BGPPeerExpansion interface{}

type ClusterInformationExpansion interface{}

type FelixConfigurationExpansion interface{}

type GlobalAlertExpansion interface{}

type GlobalAlertTemplateExpansion interface{}

type GlobalNetworkPolicyExpansion interface{}

type GlobalNetworkSetExpansion interface{}

type GlobalReportExpansion interface{}

type GlobalReportTypeExpansion interface{}

type GlobalThreatFeedExpansion interface{}

type HostEndpointExpansion interface{}

type IPPoolExpansion interface{}

type KubeControllersConfigurationExpansion interface{}

type LicenseKeyExpansion interface{}

type ManagedClusterExpansion interface{}

type NetworkPolicyExpansion interface{}

type NetworkSetExpansion interface{}

type PacketCaptureExpansion interface{}

type ProfileExpansion interface{}

type RemoteClusterConfigurationExpansion interface{}

type StagedGlobalNetworkPolicyExpansion interface{}

type StagedKubernetesNetworkPolicyExpansion interface{}

type StagedNetworkPolicyExpansion interface{}

type TierExpansion interface{}
