// Copyright (c) 2018 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package internalversion

type GlobalNetworkPolicyExpansion interface{}

type GlobalNetworkSetExpansion interface{}

type NetworkPolicyExpansion interface{}

type TierExpansion interface{}
