// Copyright (c) 2019 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	projectcalico "github.com/tigera/calico-k8sapiserver/pkg/apis/projectcalico"
	scheme "github.com/tigera/calico-k8sapiserver/pkg/client/clientset_generated/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlobalReportsGetter has a method to return a GlobalReportInterface.
// A group's client should implement this interface.
type GlobalReportsGetter interface {
	GlobalReports() GlobalReportInterface
}

// GlobalReportInterface has methods to work with GlobalReport resources.
type GlobalReportInterface interface {
	Create(*projectcalico.GlobalReport) (*projectcalico.GlobalReport, error)
	Update(*projectcalico.GlobalReport) (*projectcalico.GlobalReport, error)
	UpdateStatus(*projectcalico.GlobalReport) (*projectcalico.GlobalReport, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*projectcalico.GlobalReport, error)
	List(opts v1.ListOptions) (*projectcalico.GlobalReportList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *projectcalico.GlobalReport, err error)
	GlobalReportExpansion
}

// globalReports implements GlobalReportInterface
type globalReports struct {
	client rest.Interface
}

// newGlobalReports returns a GlobalReports
func newGlobalReports(c *ProjectcalicoClient) *globalReports {
	return &globalReports{
		client: c.RESTClient(),
	}
}

// Get takes name of the globalReport, and returns the corresponding globalReport object, and an error if there is any.
func (c *globalReports) Get(name string, options v1.GetOptions) (result *projectcalico.GlobalReport, err error) {
	result = &projectcalico.GlobalReport{}
	err = c.client.Get().
		Resource("globalreports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalReports that match those selectors.
func (c *globalReports) List(opts v1.ListOptions) (result *projectcalico.GlobalReportList, err error) {
	result = &projectcalico.GlobalReportList{}
	err = c.client.Get().
		Resource("globalreports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalReports.
func (c *globalReports) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("globalreports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a globalReport and creates it.  Returns the server's representation of the globalReport, and an error, if there is any.
func (c *globalReports) Create(globalReport *projectcalico.GlobalReport) (result *projectcalico.GlobalReport, err error) {
	result = &projectcalico.GlobalReport{}
	err = c.client.Post().
		Resource("globalreports").
		Body(globalReport).
		Do().
		Into(result)
	return
}

// Update takes the representation of a globalReport and updates it. Returns the server's representation of the globalReport, and an error, if there is any.
func (c *globalReports) Update(globalReport *projectcalico.GlobalReport) (result *projectcalico.GlobalReport, err error) {
	result = &projectcalico.GlobalReport{}
	err = c.client.Put().
		Resource("globalreports").
		Name(globalReport.Name).
		Body(globalReport).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *globalReports) UpdateStatus(globalReport *projectcalico.GlobalReport) (result *projectcalico.GlobalReport, err error) {
	result = &projectcalico.GlobalReport{}
	err = c.client.Put().
		Resource("globalreports").
		Name(globalReport.Name).
		SubResource("status").
		Body(globalReport).
		Do().
		Into(result)
	return
}

// Delete takes name of the globalReport and deletes it. Returns an error if one occurs.
func (c *globalReports) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("globalreports").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalReports) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("globalreports").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched globalReport.
func (c *globalReports) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *projectcalico.GlobalReport, err error) {
	result = &projectcalico.GlobalReport{}
	err = c.client.Patch(pt).
		Resource("globalreports").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
